"""错误码注册表 —— 与 architecture/api-conventions.md §8 一一对应。

硬性约定（BR-05 / BR-16）：
1. 新增错误码必须先在架构文档 §8 登记，再在此实现，并在同一 PR 内
   同步前端 ErrorCode 常量与 OpenAPI ErrorEnvelope（CI 三方校验）。
2. 错误码一经发布永不修改语义、永不复用；废弃码保留并标记 DEPRECATED。
3. 值为 (错误码, HTTP 状态码) 二元组；HTTP 码与 §4.3 状态码表严格一致。
"""
from rest_framework import status


class ErrorCodes:
    # ── §8.2 认证错误 AUTH_* ──────────────────────────────
    AUTH_REQUIRED            = ("AUTH_REQUIRED", status.HTTP_401_UNAUTHORIZED)
    AUTH_SESSION_EXPIRED     = ("AUTH_SESSION_EXPIRED", status.HTTP_401_UNAUTHORIZED)
    AUTH_INVALID_CREDENTIALS = ("AUTH_INVALID_CREDENTIALS", status.HTTP_401_UNAUTHORIZED)
    AUTH_INVALID_TOKEN       = ("AUTH_INVALID_TOKEN", status.HTTP_401_UNAUTHORIZED)
    AUTH_TOKEN_EXPIRED       = ("AUTH_TOKEN_EXPIRED", status.HTTP_401_UNAUTHORIZED)
    AUTH_TOKEN_REVOKED       = ("AUTH_TOKEN_REVOKED", status.HTTP_401_UNAUTHORIZED)
    AUTH_ACCOUNT_DISABLED    = ("AUTH_ACCOUNT_DISABLED", status.HTTP_401_UNAUTHORIZED)
    AUTH_EMAIL_NOT_VERIFIED  = ("AUTH_EMAIL_NOT_VERIFIED", status.HTTP_401_UNAUTHORIZED)
    AUTH_MFA_REQUIRED        = ("AUTH_MFA_REQUIRED", status.HTTP_401_UNAUTHORIZED)            # P3
    AUTH_SSO_REQUIRED        = ("AUTH_SSO_REQUIRED", status.HTTP_401_UNAUTHORIZED)            # P3
    AUTH_PASSWORD_RESET_INVALID = ("AUTH_PASSWORD_RESET_INVALID", status.HTTP_400_BAD_REQUEST)
    AUTH_PASSWORD_RESET_EXPIRED = ("AUTH_PASSWORD_RESET_EXPIRED", status.HTTP_400_BAD_REQUEST)
    AUTH_TOO_MANY_ATTEMPTS   = ("AUTH_TOO_MANY_ATTEMPTS", status.HTTP_429_TOO_MANY_REQUESTS)
    AUTH_OAUTH_INVALID_GRANT = ("AUTH_OAUTH_INVALID_GRANT", status.HTTP_400_BAD_REQUEST)      # P2
    AUTH_OAUTH_INVALID_CLIENT = ("AUTH_OAUTH_INVALID_CLIENT", status.HTTP_401_UNAUTHORIZED)   # P2
    AUTH_OAUTH_INVALID_SCOPE = ("AUTH_OAUTH_INVALID_SCOPE", status.HTTP_400_BAD_REQUEST)      # P2
    AUTH_CSRF_FAILED         = ("AUTH_CSRF_FAILED", status.HTTP_403_FORBIDDEN)

    # ── §8.3 权限错误 PERM_* ──────────────────────────────
    PERM_DENIED                = ("PERM_DENIED", status.HTTP_403_FORBIDDEN)
    PERM_ROLE_INSUFFICIENT     = ("PERM_ROLE_INSUFFICIENT", status.HTTP_403_FORBIDDEN)
    PERM_PROJECT_ADMIN_REQUIRED = ("PERM_PROJECT_ADMIN_REQUIRED", status.HTTP_403_FORBIDDEN)    # Sprint 5 注册
    PERM_WORKSPACE_ADMIN_REQUIRED = ("PERM_WORKSPACE_ADMIN_REQUIRED", status.HTTP_403_FORBIDDEN) # Sprint 5 注册
    PERM_WORKSPACE_OWNER_REQUIRED = ("PERM_WORKSPACE_OWNER_REQUIRED", status.HTTP_403_FORBIDDEN) # Sprint 5 注册
    PERM_NOT_WORKSPACE_MEMBER  = ("PERM_NOT_WORKSPACE_MEMBER", status.HTTP_403_FORBIDDEN)
    PERM_NOT_PROJECT_MEMBER    = ("PERM_NOT_PROJECT_MEMBER", status.HTTP_403_FORBIDDEN)
    PERM_PROJECT_ARCHIVED      = ("PERM_PROJECT_ARCHIVED", status.HTTP_403_FORBIDDEN)
    PERM_PROJECT_CLOSED        = ("PERM_PROJECT_CLOSED", status.HTTP_403_FORBIDDEN)             # Sprint 5 PROJ-003 注册
    PERM_WORKSPACE_ARCHIVED    = ("PERM_WORKSPACE_ARCHIVED", status.HTTP_403_FORBIDDEN)
    PERM_FIELD_READ_ONLY       = ("PERM_FIELD_READ_ONLY", status.HTTP_403_FORBIDDEN)          # P3
    PERM_FIELD_HIDDEN          = ("PERM_FIELD_HIDDEN", status.HTTP_403_FORBIDDEN)             # P3
    PERM_TRANSITION_NOT_ALLOWED = ("PERM_TRANSITION_NOT_ALLOWED", status.HTTP_403_FORBIDDEN)  # P3
    PERM_APPROVAL_NOT_ASSIGNEE  = ("PERM_APPROVAL_NOT_ASSIGNEE", status.HTTP_403_FORBIDDEN)   # P3
    PERM_LICENSE_REQUIRED      = ("PERM_LICENSE_REQUIRED", status.HTTP_403_FORBIDDEN)
    PERM_SEAT_LIMIT_EXCEEDED   = ("PERM_SEAT_LIMIT_EXCEEDED", status.HTTP_403_FORBIDDEN)
    PERM_IP_NOT_ALLOWED        = ("PERM_IP_NOT_ALLOWED", status.HTTP_403_FORBIDDEN)           # P3
    PERM_TOKEN_SCOPE_INSUFFICIENT = ("PERM_TOKEN_SCOPE_INSUFFICIENT", status.HTTP_403_FORBIDDEN)  # P2

    # ── §8.4 校验错误 VALIDATION_* ────────────────────────
    VALIDATION_ERROR               = ("VALIDATION_ERROR", status.HTTP_400_BAD_REQUEST)
    VALIDATION_INVALID_JSON        = ("VALIDATION_INVALID_JSON", status.HTTP_400_BAD_REQUEST)
    VALIDATION_INVALID_PARAM       = ("VALIDATION_INVALID_PARAM", status.HTTP_400_BAD_REQUEST)
    VALIDATION_INVALID_CURSOR      = ("VALIDATION_INVALID_CURSOR", status.HTTP_400_BAD_REQUEST)
    VALIDATION_UNSUPPORTED_MEDIA_TYPE = ("VALIDATION_UNSUPPORTED_MEDIA_TYPE", status.HTTP_415_UNSUPPORTED_MEDIA_TYPE)
    VALIDATION_PAYLOAD_TOO_LARGE   = ("VALIDATION_PAYLOAD_TOO_LARGE", status.HTTP_413_REQUEST_ENTITY_TOO_LARGE)
    VALIDATION_BULK_LIMIT_EXCEEDED = ("VALIDATION_BULK_LIMIT_EXCEEDED", status.HTTP_400_BAD_REQUEST)
    VALIDATION_FILE_TYPE_NOT_ALLOWED = ("VALIDATION_FILE_TYPE_NOT_ALLOWED", status.HTTP_400_BAD_REQUEST)
    VALIDATION_FILE_SIZE_EXCEEDED  = ("VALIDATION_FILE_SIZE_EXCEEDED", status.HTTP_400_BAD_REQUEST)
    VALIDATION_FILE_UPLOAD_MISMATCH = ("VALIDATION_FILE_UPLOAD_MISMATCH", status.HTTP_400_BAD_REQUEST)  # FILE-001 注册
    VALIDATION_INVALID_DATE_RANGE  = ("VALIDATION_INVALID_DATE_RANGE", status.HTTP_400_BAD_REQUEST)
    VALIDATION_CUSTOM_FIELD_INVALID = ("VALIDATION_CUSTOM_FIELD_INVALID", status.HTTP_400_BAD_REQUEST)  # P2
    VALIDATION_REQUIRED_FIELD_MISSING = ("VALIDATION_REQUIRED_FIELD_MISSING", status.HTTP_400_BAD_REQUEST)  # P3
    VALIDATION_ESTIMATE_REQUIRED   = ("VALIDATION_ESTIMATE_REQUIRED", status.HTTP_400_BAD_REQUEST)  # P2

    # ── §8.5 资源错误 RESOURCE_* ──────────────────────────
    RESOURCE_NOT_FOUND            = ("RESOURCE_NOT_FOUND", status.HTTP_404_NOT_FOUND)
    RESOURCE_GONE                 = ("RESOURCE_GONE", status.HTTP_410_GONE)
    RESOURCE_ALREADY_EXISTS       = ("RESOURCE_ALREADY_EXISTS", status.HTTP_409_CONFLICT)
    RESOURCE_CONFLICT             = ("RESOURCE_CONFLICT", status.HTTP_409_CONFLICT)
    RESOURCE_STATE_INVALID        = ("RESOURCE_STATE_INVALID", status.HTTP_409_CONFLICT)
    RESOURCE_TRANSITION_INVALID   = ("RESOURCE_TRANSITION_INVALID", status.HTTP_409_CONFLICT)      # P3
    RESOURCE_TRANSITION_BLOCKED   = ("RESOURCE_TRANSITION_BLOCKED", status.HTTP_409_CONFLICT)      # P2
    RESOURCE_CIRCULAR_DEPENDENCY  = ("RESOURCE_CIRCULAR_DEPENDENCY", status.HTTP_409_CONFLICT)    # P2
    RESOURCE_IN_USE               = ("RESOURCE_IN_USE", status.HTTP_409_CONFLICT)
    RESOURCE_LIMIT_EXCEEDED       = ("RESOURCE_LIMIT_EXCEEDED", status.HTTP_409_CONFLICT)
    RESOURCE_LOCKED               = ("RESOURCE_LOCKED", status.HTTP_409_CONFLICT)                 # P3

    # ── §8.6 服务端错误 SERVER_* ──────────────────────────
    SERVER_ERROR                      = ("SERVER_ERROR", status.HTTP_500_INTERNAL_SERVER_ERROR)
    SERVER_DATABASE_ERROR             = ("SERVER_DATABASE_ERROR", status.HTTP_500_INTERNAL_SERVER_ERROR)
    SERVER_STORAGE_ERROR              = ("SERVER_STORAGE_ERROR", status.HTTP_500_INTERNAL_SERVER_ERROR)      # FILE-001
    SERVER_QUEUE_ERROR                = ("SERVER_QUEUE_ERROR", status.HTTP_500_INTERNAL_SERVER_ERROR)
    SERVER_EMAIL_ERROR                = ("SERVER_EMAIL_ERROR", status.HTTP_500_INTERNAL_SERVER_ERROR)
    SERVER_EXTERNAL_SERVICE_ERROR     = ("SERVER_EXTERNAL_SERVICE_ERROR", status.HTTP_502_BAD_GATEWAY)       # INTG-*
    SERVER_LIVE_SERVICE_UNAVAILABLE   = ("SERVER_LIVE_SERVICE_UNAVAILABLE",
                                          status.HTTP_503_SERVICE_UNAVAILABLE)  # COLLAB-004
    SERVER_MAINTENANCE                = ("SERVER_MAINTENANCE", status.HTTP_503_SERVICE_UNAVAILABLE)
    SERVER_TIMEOUT                    = ("SERVER_TIMEOUT", status.HTTP_504_GATEWAY_TIMEOUT)
    SERVER_NOT_IMPLEMENTED            = ("SERVER_NOT_IMPLEMENTED", status.HTTP_501_NOT_IMPLEMENTED)

    # ── §8.7 限流与配额 RATE_* / QUOTA_* ──────────────────
    RATE_LIMIT_EXCEEDED    = ("RATE_LIMIT_EXCEEDED", status.HTTP_429_TOO_MANY_REQUESTS)   # INFRA-005 填充
    QUOTA_STORAGE_EXCEEDED = ("QUOTA_STORAGE_EXCEEDED", status.HTTP_409_CONFLICT)          # P2
    QUOTA_MEMBER_EXCEEDED  = ("QUOTA_MEMBER_EXCEEDED", status.HTTP_409_CONFLICT)           # P3
    QUOTA_PROJECT_EXCEEDED = ("QUOTA_PROJECT_EXCEEDED", status.HTTP_409_CONFLICT)          # P3
    QUOTA_AI_EXCEEDED      = ("QUOTA_AI_EXCEEDED", status.HTTP_409_CONFLICT)               # P4 AI-001 注册

    @classmethod
    def all(cls) -> dict[str, int]:
        """{(code, http_status)} 全集 —— UT-01 与 CI 校验的数据源"""
        return {
            value[0]: value[1]
            for key, value in vars(cls).items()
            if isinstance(value, tuple) and len(value) == 2
        }


#: 面向用户的默认中文文案；AppException 未传 message 时使用。
#: 文案可随版本调整（客户端禁止匹配文案，只允许按 code 分支——§8.1）。
DEFAULT_MESSAGES: dict[str, str] = {
    # ── AUTH_* ──
    "AUTH_REQUIRED": "请先登录",
    "AUTH_SESSION_EXPIRED": "登录已过期，请重新登录",
    "AUTH_INVALID_CREDENTIALS": "邮箱或密码错误",
    "AUTH_INVALID_TOKEN": "令牌无效，请重新登录",
    "AUTH_TOKEN_EXPIRED": "令牌已过期，请重新登录",
    "AUTH_TOKEN_REVOKED": "令牌已被撤销",
    "AUTH_ACCOUNT_DISABLED": "账号已被禁用，请联系管理员",
    "AUTH_EMAIL_NOT_VERIFIED": "邮箱尚未验证，请先完成验证",
    "AUTH_MFA_REQUIRED": "需要完成二次验证",
    "AUTH_SSO_REQUIRED": "请通过企业 SSO 登录",
    "AUTH_PASSWORD_RESET_INVALID": "密码重置链接无效",
    "AUTH_PASSWORD_RESET_EXPIRED": "密码重置链接已过期，请重新申请",
    "AUTH_TOO_MANY_ATTEMPTS": "尝试次数过多，请稍后再试",
    "AUTH_OAUTH_INVALID_GRANT": "授权码无效或已过期",
    "AUTH_OAUTH_INVALID_CLIENT": "OAuth 客户端凭据无效",
    "AUTH_OAUTH_INVALID_SCOPE": "请求的权限范围不被允许",
    "AUTH_CSRF_FAILED": "安全校验失败，正在自动重试",

    # ── PERM_* ──
    "PERM_DENIED": "你没有执行此操作的权限",
    "PERM_ROLE_INSUFFICIENT": "当前角色权限不足",
    "PERM_PROJECT_ADMIN_REQUIRED": "需要项目管理员权限",
    "PERM_WORKSPACE_ADMIN_REQUIRED": "需要工作空间管理员权限",
    "PERM_WORKSPACE_OWNER_REQUIRED": "需要工作空间所有者权限",
    "PERM_NOT_WORKSPACE_MEMBER": "你不是该工作空间的成员",
    "PERM_NOT_PROJECT_MEMBER": "你不是该项目的成员",
    "PERM_PROJECT_ARCHIVED": "项目已归档，不允许修改",
    "PERM_PROJECT_CLOSED": "项目已关闭，不允许修改",
    "PERM_WORKSPACE_ARCHIVED": "工作空间已归档，不允许修改",
    "PERM_FIELD_READ_ONLY": "该字段为只读",
    "PERM_FIELD_HIDDEN": "该字段不可见",
    "PERM_TRANSITION_NOT_ALLOWED": "当前状态不允许此流转",
    "PERM_APPROVAL_NOT_ASSIGNEE": "仅审批人本人可以处理此审批",
    "PERM_LICENSE_REQUIRED": "需要有效的许可证",
    "PERM_SEAT_LIMIT_EXCEEDED": "席位数量已达上限",
    "PERM_IP_NOT_ALLOWED": "当前 IP 不在允许访问范围内",
    "PERM_TOKEN_SCOPE_INSUFFICIENT": "令牌权限范围不足",

    # ── VALIDATION_* ──
    "VALIDATION_ERROR": "请求参数校验失败",
    "VALIDATION_INVALID_JSON": "请求体不是合法的 JSON",
    "VALIDATION_INVALID_PARAM": "请求参数不合法",
    "VALIDATION_INVALID_CURSOR": "游标参数无效",
    "VALIDATION_UNSUPPORTED_MEDIA_TYPE": "不支持的媒体类型",
    "VALIDATION_PAYLOAD_TOO_LARGE": "请求体过大，请使用附件直传通道",
    "VALIDATION_BULK_LIMIT_EXCEEDED": "批量操作数量超过上限",
    "VALIDATION_FILE_TYPE_NOT_ALLOWED": "不支持的文件类型",
    "VALIDATION_FILE_SIZE_EXCEEDED": "文件大小超过限制",
    "VALIDATION_FILE_UPLOAD_MISMATCH": "文件上传参数不匹配",
    "VALIDATION_INVALID_DATE_RANGE": "日期范围不合法",
    "VALIDATION_CUSTOM_FIELD_INVALID": "自定义字段值不合法",
    "VALIDATION_REQUIRED_FIELD_MISSING": "必填字段缺失",
    "VALIDATION_ESTIMATE_REQUIRED": "需要填写工作量估算",

    # ── RESOURCE_* ──
    "RESOURCE_NOT_FOUND": "资源不存在或你没有访问权限",
    "RESOURCE_GONE": "资源已永久删除",
    "RESOURCE_ALREADY_EXISTS": "该名称已被使用",
    "RESOURCE_CONFLICT": "该数据已被他人修改，请刷新后重试",
    "RESOURCE_STATE_INVALID": "资源当前状态不允许此操作",
    "RESOURCE_TRANSITION_INVALID": "状态流转不合法",
    "RESOURCE_TRANSITION_BLOCKED": "状态流转被前置条件阻止",
    "RESOURCE_CIRCULAR_DEPENDENCY": "存在循环依赖",
    "RESOURCE_IN_USE": "资源正在被使用，无法删除",
    "RESOURCE_LIMIT_EXCEEDED": "资源数量已达上限",
    "RESOURCE_LOCKED": "资源已被锁定，请稍后再试",

    # ── SERVER_* ──
    "SERVER_ERROR": "服务器开小差了，请稍后重试",
    "SERVER_DATABASE_ERROR": "数据库暂时不可用，请稍后重试",
    "SERVER_STORAGE_ERROR": "对象存储暂时不可用，请稍后重试",
    "SERVER_QUEUE_ERROR": "消息队列暂时不可用，请稍后重试",
    "SERVER_EMAIL_ERROR": "邮件服务暂时不可用，请稍后重试",
    "SERVER_EXTERNAL_SERVICE_ERROR": "服务暂不可用，请稍后重试",
    "SERVER_LIVE_SERVICE_UNAVAILABLE": "实时协作服务暂不可用",
    "SERVER_MAINTENANCE": "系统维护中，请稍后再来",
    "SERVER_TIMEOUT": "请求超时，请重试",
    "SERVER_NOT_IMPLEMENTED": "该能力尚未实现",

    # ── RATE_* / QUOTA_* ──
    "RATE_LIMIT_EXCEEDED": "请求过于频繁，请稍后重试",
    "QUOTA_STORAGE_EXCEEDED": "存储配额已用完",
    "QUOTA_MEMBER_EXCEEDED": "成员数量已达上限",
    "QUOTA_PROJECT_EXCEEDED": "项目数量已达上限",
    "QUOTA_AI_EXCEEDED": "AI 调用配额已用完",
}
