# Generated by Django 5.1.15 on 2026-09-02 06:27

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='邮箱')),
                ('display_name', models.CharField(max_length=150, verbose_name='显示名')),
                ('avatar_url', models.URLField(blank=True, max_length=800, verbose_name='头像地址')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最近登录时间')),
                ('last_workspace_id', models.UUIDField(blank=True, null=True, verbose_name='最近访问的工作空间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=512, verbose_name='标题')),
                ('description_json', models.JSONField(blank=True, default=dict, verbose_name='描述-ProseMirror JSON')),
                ('description_html', models.TextField(blank=True, default='<p></p>', verbose_name='描述-HTML')),
                ('description_binary', models.BinaryField(blank=True, null=True, verbose_name='描述-Yjs Binary')),
                ('description_stripped', models.TextField(blank=True, null=True, verbose_name='描述-纯文本')),
                ('priority', models.CharField(choices=[('none', '无'), ('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], db_index=True, default='none', max_length=16, verbose_name='优先级')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('target_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='截止时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('sequence_id', models.IntegerField(default=1, verbose_name='项目内序列号')),
                ('sort_order', models.FloatField(default=65535.0, verbose_name='排序值')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='自定义字段值')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_issues', to='db.issue', verbose_name='父工作项')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '工作项',
                'db_table': 'issues',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueActivity',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('verb', models.CharField(choices=[('created', '创建'), ('updated', '更新'), ('deleted', '删除')], default='created', max_length=16, verbose_name='动作')),
                ('field', models.CharField(blank=True, max_length=64, null=True, verbose_name='变更字段名')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='变更前值')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='变更后值')),
                ('old_identifier', models.UUIDField(blank=True, null=True, verbose_name='变更前关联对象 ID')),
                ('new_identifier', models.UUIDField(blank=True, null=True, verbose_name='变更后关联对象 ID')),
                ('comment', models.TextField(blank=True, verbose_name='人类可读描述')),
                ('epoch', models.FloatField(null=True, verbose_name='毫秒时间戳')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_activities', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_activities', to='db.issue', verbose_name='工作项')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '工作项操作日志',
                'db_table': 'issue_activities',
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueAssignee',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issue_records', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignees', to='db.issue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '工作项负责人',
                'db_table': 'issue_assignees',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_issues', through='db.IssueAssignee', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.CreateModel(
            name='IssueLink',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('relation_type', models.CharField(choices=[('blocks', '阻塞'), ('is_blocked_by', '被阻塞于'), ('relates_to', '关联'), ('duplicates', '重复于')], default='relates_to', max_length=24, verbose_name='关联类型')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='db.issue', verbose_name='源工作项')),
                ('related_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_issue_links', to='db.issue', verbose_name='目标工作项')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '工作项关联',
                'db_table': 'issue_links',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, verbose_name='类型说明')),
                ('icon', models.CharField(default='circle-dot', max_length=64, verbose_name='图标')),
                ('color', models.CharField(default='#6B7280', max_length=9, verbose_name='主题色')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认类型')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否内置')),
                ('sort_order', models.PositiveIntegerField(default=1000, verbose_name='显示排序')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '任务类型',
                'db_table': 'issue_types',
                'ordering': ('sort_order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='db.issuetype', verbose_name='任务类型'),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='标签名称')),
                ('color', models.CharField(default='#6B7280', max_length=9, verbose_name='标签颜色')),
                ('sort_order', models.FloatField(default=65535.0, verbose_name='排序值')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '标签',
                'db_table': 'labels',
                'ordering': ('sort_order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueLabel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_labels', to='db.issue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_labels', to='db.label')),
            ],
            options={
                'verbose_name': '工作项标签',
                'db_table': 'issue_labels',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='issues', through='db.IssueLabel', to='db.label', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('identifier', models.CharField(help_text='工作项编号前缀', max_length=12, verbose_name='项目标识')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('archived', '已归档'), ('closed', '已关闭')], db_index=True, default='active', max_length=16, verbose_name='项目状态')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '项目',
                'db_table': 'projects',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='db.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='db.project', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='状态名称')),
                ('color', models.CharField(default='#6B7280', max_length=9, verbose_name='状态颜色')),
                ('group', models.CharField(choices=[('backlog', '待规划'), ('unstarted', '未开始'), ('started', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='backlog', max_length=16, verbose_name='语义分组')),
                ('sort_order', models.FloatField(default=65535.0, verbose_name='排序值')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认状态')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='db.issuetype', verbose_name='专属任务类型')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '任务状态',
                'db_table': 'states',
                'ordering': ('sort_order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='db.state', verbose_name='当前状态'),
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_ip_cidrs', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_system_admins', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '系统管理员',
                'db_table': 'system_admins',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('slug', models.SlugField(max_length=48, verbose_name='URL 标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('logo', models.URLField(blank=True, max_length=800, null=True, verbose_name='Logo 地址')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '工作空间',
                'db_table': 'workspaces',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('role', models.IntegerField(choices=[(20, 'Admin'), (15, 'Contributor'), (10, 'Commenter'), (5, 'Viewer')], default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('view_props', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_project', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_projectmember', to='db.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_member', to='db.workspace')),
            ],
            options={
                'verbose_name': '项目成员',
                'db_table': 'project_members',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='db.workspace', verbose_name='所属工作空间'),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_types', to='db.workspace', verbose_name='所属工作空间'),
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('role', models.IntegerField(choices=[(20, 'Owner'), (15, 'Admin'), (10, 'Member'), (5, 'Guest')], default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company_role', models.TextField(blank=True, null=True, verbose_name='公司内职务')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_workspace', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_member', to='db.workspace')),
            ],
            options={
                'verbose_name': '工作空间成员',
                'db_table': 'workspace_members',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='users_email_a7cfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='issueactivity',
            index=models.Index(fields=['issue', 'created_at'], name='idx_activity_issue_time'),
        ),
        migrations.AddIndex(
            model_name='issueactivity',
            index=models.Index(fields=['actor', 'created_at'], name='idx_activity_actor_time'),
        ),
        migrations.AddIndex(
            model_name='issueactivity',
            index=models.Index(fields=['field'], name='idx_activity_field'),
        ),
        migrations.AddIndex(
            model_name='issueassignee',
            index=models.Index(fields=['assignee', 'issue'], name='idx_assignee_issue'),
        ),
        migrations.AddConstraint(
            model_name='issueassignee',
            constraint=models.UniqueConstraint(fields=('issue', 'assignee'), name='uniq_issue_assignee'),
        ),
        migrations.AddIndex(
            model_name='issuelink',
            index=models.Index(fields=['issue', 'relation_type'], name='idx_link_issue_type'),
        ),
        migrations.AddIndex(
            model_name='issuelink',
            index=models.Index(fields=['related_issue', 'relation_type'], name='idx_link_related_type'),
        ),
        migrations.AddConstraint(
            model_name='issuelink',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'related_issue', 'relation_type'), name='uniq_issue_relation'),
        ),
        migrations.AddConstraint(
            model_name='issuelink',
            constraint=models.CheckConstraint(condition=models.Q(('issue', models.F('related_issue')), _negated=True), name='chk_issue_link_no_self'),
        ),
        migrations.AddConstraint(
            model_name='issuelabel',
            constraint=models.UniqueConstraint(fields=('issue', 'label'), name='uniq_issue_label'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name'), name='uniq_label_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name', 'issue_type'), name='uniq_state_name_per_project_type'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('project', 'issue_type'), name='uniq_default_state_per_project_type'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'state', 'sort_order'], name='idx_issue_proj_state_sort'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'issue_type'], name='idx_issue_proj_type'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['parent'], name='idx_issue_parent'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(condition=models.Q(('archived_at__isnull', True), ('deleted_at__isnull', True)), fields=['project', 'created_at'], name='idx_issue_active_by_project'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=django.contrib.postgres.indexes.GinIndex(fields=['custom_fields'], name='idx_issue_custom_fields'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_stripped'], name='idx_issue_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'sequence_id'), name='uniq_issue_sequence_per_project'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('target_date__isnull', True), ('start_date__lte', models.F('target_date')), _connector='OR'), name='chk_issue_start_before_target'),
        ),
        migrations.AddIndex(
            model_name='systemadmin',
            index=models.Index(fields=['user', 'is_active'], name='system_admi_user_id_4631be_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='uniq_workspace_slug_alive'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['member', 'project', 'role'], name='project_mem_member__fd8f80_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['member', 'workspace'], name='project_mem_member__24476b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'member')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'status'], name='idx_project_ws_status'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'identifier'), name='uniq_project_identifier_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='issuetype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='uniq_issue_type_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='issuetype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('workspace',), name='uniq_default_issue_type_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['member', 'workspace', 'role'], name='workspace_m_member__824554_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['workspace', 'role'], name='workspace_m_workspa_4fb2fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together={('workspace', 'member')},
        ),
    ]
