# Generated by Django 5.1.15 on 2026-09-03 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('entity_type', models.CharField(choices=[('issue', '任务'), ('avatar', '头像')], max_length=32, verbose_name='宿主类型')),
                ('entity_id', models.UUIDField(verbose_name='宿主实体 ID')),
                ('attributes', models.JSONField(default=dict, help_text='{"name":"error-500.png","size":2097152,"mime":"image/png","ext":".png"}', verbose_name='原始属性')),
                ('size', models.BigIntegerField(db_index=True, default=0, verbose_name='字节数')),
                ('storage_path', models.TextField(help_text='ws/proj/entity_type/entity_id/{ulid}.{ext}', verbose_name='对象键')),
                ('status', models.CharField(choices=[('uploading', '直传中'), ('uploaded', '已上传'), ('abandoned', '已弃置')], db_index=True, default='uploading', max_length=16, verbose_name='上传状态')),
                ('is_uploaded', models.BooleanField(default=False, help_text='status=uploaded 的冗余布尔，兼容 Plane 语义', verbose_name='完成确认位')),
            ],
            options={
                'verbose_name': '文件资产',
                'db_table': 'file_assets',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('comment_json', models.JSONField(blank=True, default=dict, help_text='Tiptap 编辑器原生格式，编辑回显用', verbose_name='评论-ProseMirror JSON')),
                ('comment_html', models.TextField(verbose_name='评论 HTML（净化后）')),
                ('comment_stripped', models.TextField(help_text='长度校验 / 搜索 / 通知摘要', verbose_name='纯文本')),
                ('accessory', models.JSONField(blank=True, default=dict, help_text='P2: {"reactions":[{"emoji":"👍","user_ids":[…]}],"images":[asset_id,…]}', verbose_name='扩展数据')),
                ('is_edited', models.BooleanField(default=False, verbose_name='是否编辑过')),
            ],
            options={
                'verbose_name': '任务评论',
                'db_table': 'issue_comments',
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('event', models.CharField(choices=[('issue.assigned', '被指派'), ('issue.mentioned', '被提及'), ('issue.commented', '任务被评论'), ('issue.updated', '任务被更新')], db_index=True, max_length=32, verbose_name='事件类型')),
                ('title', models.CharField(help_text='可直接展示的完整文案', max_length=200, verbose_name='标题')),
                ('data', models.JSONField(default=dict, help_text='必含 issue_id/project_id/workspace_slug/issue_key/actor + 事件特有键', verbose_name='跳转载荷')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='已读时间')),
                ('dedup_key', models.CharField(blank=True, default='', help_text='sha256(event+issue+actor+epoch+receiver)——worker 重试/MQ 重投零重复', max_length=64, verbose_name='幂等键')),
            ],
            options={
                'verbose_name': '站内通知',
                'db_table': 'notifications',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SHA-256(令牌)')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='申请来源 IP')),
            ],
            options={
                'verbose_name': '密码重置令牌',
                'db_table': 'password_reset_tokens',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectFavorite',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '项目收藏',
                'db_table': 'project_favorites',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMemberInvite',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('email', models.EmailField(max_length=254, verbose_name='被邀邮箱（归一小写）')),
                ('role', models.IntegerField(choices=[(20, 'Owner'), (15, 'Admin'), (10, 'Member'), (5, 'Guest')], default=10, help_text='仅允许 MEMBER(10) / ADMIN(15)，Service 层校验（BR-02）', verbose_name='预设角色')),
                ('token_hash', models.CharField(db_index=True, help_text='接受端点按 hash 检索，token 明文不落库', max_length=64, unique=True, verbose_name='SHA-256(token)')),
                ('status', models.CharField(choices=[('pending', '待接受'), ('accepted', '已接受'), ('revoked', '已撤销'), ('expired', '已过期')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='接受时间')),
            ],
            options={
                'verbose_name': '工作空间邀请',
                'db_table': 'workspace_member_invites',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='attachment_count',
            field=models.IntegerField(default=0, help_text='F() 维护，列表 / 看板卡片徽标消费（FILE-001 §4.1 §2.3 BR-09）', verbose_name='附件计数'),
        ),
        migrations.AddField(
            model_name='label',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='停用后不可新挂载；已挂载卡片淡显保留（BR-05）', verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, default='', help_text='≤500 字符；纯文本（无富文本），列表/提及浮层可截断展示', max_length=500, verbose_name='个人简介'),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['project', 'is_active'], name='idx_label_project_active'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='project',
            field=models.ForeignKey(blank=True, help_text='头像等无项目实体为 NULL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='db.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='db.workspace', verbose_name='所属工作空间'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='db.issue', verbose_name='所属任务'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P1 恒为 NULL；P2 楼中楼两级结构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='db.issuecomment', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='projectfavorite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='projectfavorite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='db.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectfavorite',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='projectfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='workspacememberinvite',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_workspace_invites', to=settings.AUTH_USER_MODEL, verbose_name='接受人'),
        ),
        migrations.AddField(
            model_name='workspacememberinvite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='workspacememberinvite',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_invites', to=settings.AUTH_USER_MODEL, verbose_name='邀请人'),
        ),
        migrations.AddField(
            model_name='workspacememberinvite',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='workspacememberinvite',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='db.workspace', verbose_name='目标工作空间'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_asset_entity'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['status', 'created_at'], name='idx_asset_status_time'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['workspace', 'status'], name='idx_asset_ws_status'),
        ),
        migrations.AddIndex(
            model_name='issuecomment',
            index=models.Index(fields=['issue', 'created_at'], name='idx_comment_issue_time'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'read_at', 'created_at'], name='idx_notif_receiver_unread'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['read_at', 'created_at'], name='idx_notif_retention'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedup_key', ''), _negated=True), fields=('receiver', 'dedup_key'), name='uniq_notif_dedup'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'expires_at'], name='idx_prt_user_exp'),
        ),
        migrations.AddConstraint(
            model_name='passwordresettoken',
            constraint=models.UniqueConstraint(condition=models.Q(('used_at__isnull', True)), fields=('user',), name='uniq_one_live_reset_token_per_user'),
        ),
        migrations.AddIndex(
            model_name='projectfavorite',
            index=models.Index(fields=['user', 'created_at'], name='idx_pf_user_time'),
        ),
        migrations.AddConstraint(
            model_name='projectfavorite',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'project'), name='uniq_user_project_favorite'),
        ),
        migrations.AddIndex(
            model_name='workspacememberinvite',
            index=models.Index(fields=['workspace', 'status'], name='idx_invite_ws_status'),
        ),
        migrations.AddIndex(
            model_name='workspacememberinvite',
            index=models.Index(fields=['status', 'expires_at'], name='idx_invite_status_expiry'),
        ),
        migrations.AddConstraint(
            model_name='workspacememberinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'pending')), fields=('workspace', 'email'), name='uniq_pending_invite_per_email'),
        ),
    ]
