# Generated by Django 5.1.15 on 2026-09-05 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_p1_issue_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='estimate_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='P2 分钟制；P3 视需要叠加 Estimate 点数系统（TASK-006 §4.1.1）', null=True, verbose_name='估算工时（分钟）'),
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('worked_on', models.DateField(db_index=True, verbose_name='工作日期')),
                ('minutes', models.PositiveIntegerField(help_text='1~1440，整数分钟', verbose_name='时长（分钟）')),
                ('note', models.CharField(blank=True, max_length=2000, verbose_name='备注')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL, verbose_name='填报人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='db.issue', verbose_name='所属工作项')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '工时记录',
                'verbose_name_plural': '工时记录',
                'db_table': 'work_logs',
                'ordering': ('-worked_on', '-created_at'),
                'abstract': False,
                'indexes': [models.Index(fields=['issue'], name='idx_worklog_issue'), models.Index(fields=['actor', 'worked_on'], name='idx_worklog_actor_day')],
                'constraints': [models.CheckConstraint(condition=models.Q(('minutes__gte', 1), ('minutes__lte', 1440)), name='chk_worklog_minutes_range')],
            },
        ),
    ]
