# Generated by Django 5.1.15 on 2026-09-05 11:51

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_p2_worklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(help_text='可随时修改，不影响已存数据', max_length=128, verbose_name='字段显示名')),
                ('field_key', models.CharField(help_text='JSONB 中的键名，cf_ 前缀 snake_case，创建后不可修改（BR-01）', max_length=64, verbose_name='字段键名')),
                ('field_type', models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('number', '数字'), ('select', '单选下拉'), ('multi_select', '多选下拉'), ('date', '日期'), ('member', '人员单选'), ('member_multi', '人员多选'), ('checkbox', '复选框'), ('url', 'URL 链接'), ('currency', '金额'), ('auto_increment', '自增编号'), ('cascade', '级联下拉'), ('relation', '关联工作项'), ('date_range', '日期区间'), ('attachment', '附件'), ('formula', '公式计算')], help_text='决定表单控件、筛选控件与值的 JSON 类型，创建后不可修改（BR-06）', max_length=24, verbose_name='字段类型')),
                ('description', models.TextField(blank=True, help_text='表单中以问号提示展示', verbose_name='字段帮助说明')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('default_value', models.JSONField(blank=True, help_text='新建工作项时预填，类型须与 field_type 匹配（BR-05）', null=True, verbose_name='默认值')),
                ('options', models.JSONField(blank=True, default=list, help_text='[{"label":"高","value":"high","color":"#EF4444","sort_order":1}]，option value 创建后不可改（BR-04）', verbose_name='选项配置')),
                ('sort_order', models.FloatField(default=65535.0, help_text='浮点插值，支持拖拽排序', verbose_name='显示排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='停用后表单与筛选器不再展示，历史数据保留（BR-12）', verbose_name='是否启用')),
                ('applicable_types', models.JSONField(blank=True, default=list, help_text='IssueType UUID 字符串列表，空列表表示适用于全部类型', verbose_name='适用任务类型')),
                ('is_indexed', models.BooleanField(default=False, help_text='标记后由异步任务 CONCURRENTLY 创建表达式偏索引（每 WS ≤10 个，BR-10）', verbose_name='建立专用表达式索引')),
                ('is_searchable', models.BooleanField(default=False, help_text='P2 末视性能评估启用', verbose_name='纳入全文搜索')),
                ('permission_config', models.JSONField(blank=True, default=dict, help_text='P3：{"read":["role:member"],"write":["role:admin"],"required_for":["role:member"]}', verbose_name='字段级权限配置')),
                ('cascade_config', models.JSONField(blank=True, default=dict, help_text='P3：{"parent_field_key":"cf_product_line","visible_when":{"cf_type":["bug"]}}', verbose_name='级联/联动配置')),
                ('formula', models.TextField(blank=True, help_text='P4：如 {cf_price} * {cf_quantity}', verbose_name='公式表达式')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, help_text='为空表示 Workspace 全局字段，对所有项目生效', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='db.workspace', verbose_name='所属工作空间')),
            ],
            options={
                'verbose_name': '自定义字段定义',
                'verbose_name_plural': '自定义字段定义',
                'db_table': 'custom_field_definitions',
                'ordering': ('sort_order', 'created_at'),
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', 'is_active', 'sort_order'], name='idx_cfd_ws_active'), models.Index(fields=['project', 'is_active', 'sort_order'], name='idx_cfd_proj_active'), django.contrib.postgres.indexes.GinIndex(fields=['applicable_types'], name='idx_cfd_applicable_types')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', True)), fields=('workspace', 'field_key'), name='uniq_global_field_key_per_workspace'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', False)), fields=('project', 'field_key'), name='uniq_project_field_key')],
            },
        ),
    ]
