# Generated by Django 5.1.15 on 2026-09-05 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from plane.db.seeds.project_views import seed_builtin_views


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_p2_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='{"board.default_view_id":{"<project_id>":"<view_uuid>"}}', verbose_name='用户偏好'),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='[{"label":"高","value":"high","color":"#EF4444","sort_order":1}]；option value 创建后不可改（BR-04）', verbose_name='选项配置'),
        ),
        migrations.CreateModel(
            name='IssueView',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='视图名称')),
                ('description', models.TextField(blank=True, verbose_name='视图说明')),
                ('access', models.CharField(choices=[('personal', '个人视图'), ('shared', '共享视图')], default='personal', max_length=16, verbose_name='访问范围')),
                ('layout', models.CharField(choices=[('list', '列表'), ('kanban', '看板'), ('gantt', '甘特图'), ('table', '表格')], default='list', help_text='架构 §5.6 默认 list', max_length=16, verbose_name='布局')),
                ('filters', models.JSONField(default=dict, help_text='扁平形态：{"op":"AND","conditions":[{"field":"priority","operator":"in","value":["urgent"]}]}', verbose_name='筛选条件树（DSL）')),
                ('display_props', models.JSONField(default=dict, help_text='{"icon":"🚒","group_by":"priority","order_by":"sort_order","columns":["issue_key","name","state_id","assignee_ids","target_date"],"card_fields":{"labels":true,"sub_issues":true,"attachments":true,"estimate":false,"priority":true,"timer":true,"target_date":true,"cf_severity":true},"show_empty_groups":true,"sub_group_by":null}', verbose_name='展示配置')),
                ('is_system', models.BooleanField(default=False, help_text='需求池/缺陷列表等，不可删除、filters 锁定', verbose_name='内置视图')),
                ('is_locked', models.BooleanField(default=False, verbose_name='管理员锁定（P3）')),
                ('sort_order', models.FloatField(default=65535.0, verbose_name='显示排序')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, help_text='为空表示跨项目全局视图（P3）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='db.workspace', verbose_name='所属工作空间')),
            ],
            options={
                'verbose_name': '任务视图',
                'verbose_name_plural': '任务视图',
                'db_table': 'issue_views',
                'ordering': ('sort_order', 'created_at'),
                'abstract': False,
                'indexes': [models.Index(fields=['project', 'access', 'sort_order'], name='idx_view_proj_access'), models.Index(fields=['owner', 'access'], name='idx_view_owner_access')],
            },
        ),
        # 内置五视图种子（BOARD-003 §4.1.2 双触发之一：存量项目补种；
        # 部署后新建项目由 Project 创建服务内 seed_project_views 同事务补齐）
        migrations.RunPython(seed_builtin_views, migrations.RunPython.noop),
    ]
