# Generated by Django 5.1.15 on 2026-09-05 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_p2_issue_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileasset',
            name='entity_type',
            field=models.CharField(choices=[('issue', '任务'), ('avatar', '头像'), ('comment_image', '评论图片')], max_length=32, verbose_name='宿主类型'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('issue.assigned', '被指派'), ('issue.mentioned', '被提及'), ('issue.commented', '任务被评论'), ('issue.updated', '任务被更新'), ('comment.replied', '评论被回复')], db_index=True, max_length=32, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('emoji', models.CharField(help_text='白名单 24 枚（COLLAB-002 §4.3.1），存字面量不存编码', max_length=16, verbose_name='emoji 字面量')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL, verbose_name='反应人')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='db.issuecomment', verbose_name='所属评论')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '评论表情',
                'verbose_name_plural': '评论表情',
                'db_table': 'comment_reactions',
                'ordering': ('created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['comment', 'emoji'], name='idx_reaction_comment_emoji')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('comment', 'actor', 'emoji'), name='uniq_reaction_comment_actor_emoji')],
            },
        ),
    ]
