# Generated by Django 5.1.15 on 2026-09-06 12:39，随后按 FILE-002 §4.1.3 手工补齐
# RunPython 回填与两条 RunSQL 索引（根层唯一表达式索引 BR-01 / 名称 trgm）。

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_issue_fk(apps, schema_editor):
    """§1.7 第 1 行：存量 issue 域全部行回填冗余外键 entity_id → issue_id（avatar 等其他域跳过）。"""
    FileAsset = apps.get_model("db", "FileAsset")
    FileAsset.objects.filter(entity_type="issue").update(issue_id=F("entity_id"))


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_p2_comment_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='allowed_members',
            field=models.JSONField(blank=True, default=list, verbose_name='指定可见成员（UUID 列表，members 态生效）'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='current_version',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='当前版本（FILE-003 预留）'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='下载次数'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dual_mount_files', to='db.issue', verbose_name='双挂任务（第二视图入口，可空）'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='upload_session',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='分片上传会话（FILE-003 预留）'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='visibility',
            field=models.CharField(choices=[('all', '全员可见'), ('admins', '仅项目管理员'), ('members', '指定成员')], default='all', max_length=16, verbose_name='可见性（默认随目录，可独立收紧）'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='entity_type',
            field=models.CharField(choices=[('issue', '任务'), ('avatar', '头像'), ('comment_image', '评论图片'), ('project_file', '项目文件库')], max_length=32, verbose_name='宿主类型'),
        ),
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='目录名')),
                ('visibility', models.CharField(choices=[('all', '全员可见'), ('admins', '仅项目管理员'), ('members', '指定成员')], default='all', max_length=16, verbose_name='可见性')),
                ('allowed_members', models.JSONField(blank=True, default=list, verbose_name='指定可见成员（UUID 列表，members 态生效）')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.filefolder', verbose_name='父目录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_folders', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '文件目录',
                'db_table': 'file_folders',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fileasset',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='entity_type=project_file 时与 entity_id 同值同步（写入侧保证）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='db.filefolder', verbose_name='所属目录（文件库身份，= entity_id）'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['project', 'folder'], name='idx_asset_project_folder'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['issue'], name='idx_asset_issue'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['project', 'uploaded_by', 'created_at'], name='idx_asset_project_uploader'),
        ),
        migrations.AddIndex(
            model_name='filefolder',
            index=models.Index(fields=['project', 'parent'], name='idx_folder_project_parent'),
        ),
        migrations.AddConstraint(
            model_name='filefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('parent', 'name'), name='uniq_folder_name_per_parent'),
        ),
        # ── FILE-002 §4.1.3：存量回填 + 两条 RunSQL 索引 ──
        migrations.RunPython(backfill_issue_fk, migrations.RunPython.noop),
        # 根层唯一性表达式索引（BR-01 第二层）：偏条件约束 uniq_folder_name_per_parent
        # 在 parent=NULL 时失效（PG NULL 互异）——根层同层同名由 COALESCE 归一父键后的
        # 表达式唯一索引兜底（Serializer clean 校验为第一层；project_id 入键保证跨项目
        # 根层互不影响）：
        migrations.RunSQL(
            sql="CREATE UNIQUE INDEX IF NOT EXISTS uniq_folder_name_root "
                "ON file_folders (project_id, COALESCE(parent_id::text, ''), name) "
                "WHERE deleted_at IS NULL;",
            reverse_sql="DROP INDEX IF EXISTS uniq_folder_name_root;",
        ),
        # 名称 trgm 模糊过滤索引（§4.2.1 ?name= 筛选取数；pg_trgm 扩展由 0001_extensions
        # 预建，此处不重复 CREATE EXTENSION）：
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_asset_name_trgm "
                "ON file_assets USING gin ((attributes->>'name') gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS idx_asset_name_trgm;",
        ),
    ]
