# Generated by Django 5.1.15 on 2026-09-06，随后按 FILE-003 §4.1.2 手工补齐存量
# 文件 v1 回填数据迁移（幂等）。DDL 清单与规格一致：CreateModel × 2 +
# AlterField × 1（current_version UUID 预留列 → 真 FK，§4.1.2）+ RemoveField × 1
# （upload_session OneToOne 预留列撤销——关系由 UploadSession.asset FK 承载，注 2）。

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_version_v1(apps, schema_editor):
    """为每个既有 uploaded 且无版本的 FileAsset 生成 v1 FileVersion 并回填指针。

    幂等：已有版本的资产跳过（重复执行零副作用）。attributes 形态与运行期
    ``_new_version`` 一致（name/size/content_type/md5），asset 行级镜像三列
    （storage_path/size/attributes）以既有值为准不动——回填只补版本行与指针。
    """
    FileAsset = apps.get_model("db", "FileAsset")
    FileVersion = apps.get_model("db", "FileVersion")
    # 迁移历史模型无自定义 Manager（all_objects 不可用），原生 objects 即全量
    for asset in FileAsset.objects.filter(
        status="uploaded", current_version__isnull=True
    ).iterator(chunk_size=500):
        attrs = dict(asset.attributes or {})
        attrs.setdefault("size", asset.size)
        version = FileVersion.objects.create(
            asset_id=asset.id,
            version_number=1,
            object_key=asset.storage_path,
            attributes=attrs,
            uploaded_by_id=asset.uploaded_by_id,
            created_by_id=asset.created_by_id,
            created_at=asset.created_at or timezone.now(),
        )
        FileAsset.objects.filter(pk=asset.pk).update(current_version=version.id)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_p2_file_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileasset',
            name='upload_session',
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('version_number', models.PositiveIntegerField(verbose_name='版本号（文件内递增）')),
                ('object_key', models.TextField(verbose_name='对象键（版本独立或回滚复用）')),
                ('attributes', models.JSONField(default=dict, help_text='衍生物登记也挂本列：derivatives.{kind} = {key,status,generated_at,last_access_at}', verbose_name='name/size/content_type/md5')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='db.fileasset', verbose_name='所属文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_children', to='db.fileversion', verbose_name='回滚来源')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人（complete/rollback 操作者留痕，§4.3.2）')),
            ],
            options={
                'db_table': 'file_versions',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='current_version',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_current', to='db.fileversion', verbose_name='当前版本指针（FILE-003）'),
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('s3_upload_id', models.CharField(max_length=128, verbose_name='S3 multipart id')),
                ('object_key', models.TextField(verbose_name='目标对象键')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(verbose_name='总大小')),
                ('content_type', models.CharField(max_length=128)),
                ('content_md5', models.CharField(blank=True, help_text='init 登记留痕 → complete 落 FileVersion.attributes.md5（版本元数据对比/审计，§4.2.1）；不做秒传索引（§6.2）', max_length=32, null=True, verbose_name='整件 MD5')),
                ('chunk_size', models.PositiveIntegerField(default=8388608)),
                ('total_chunks', models.PositiveIntegerField()),
                ('uploaded_chunks', models.JSONField(default=list, help_text='[{"n":1,"etag":"…","size":8388608}]', verbose_name='已完成片号')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('completed', '已完成'), ('aborted', '已取消'), ('expired', '已过期')], db_index=True, default='uploading', max_length=16)),
                ('asset', models.ForeignKey(blank=True, help_text='FK 而非 OneToOne：会话是历史账本——completed/expired 不释放、也不阻塞新会话（BR-15）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to='db.fileasset', verbose_name='目标文件（BR-07 同名匹配既有行，可空）')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='db.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'upload_sessions',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='fileversion',
            index=models.Index(fields=['asset', '-created_at'], name='idx_version_asset_recent'),
        ),
        migrations.AddConstraint(
            model_name='fileversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset', 'version_number'), name='uniq_version_per_asset'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['project', 'status'], name='idx_us_project_status'),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.UniqueConstraint(condition=models.Q(('asset__isnull', False), ('status', 'uploading')), fields=('asset',), name='uniq_active_session_per_asset'),
        ),
        # ── FILE-003 §4.1.2：存量文件 v1 回填（幂等）──
        migrations.RunPython(backfill_version_v1, migrations.RunPython.noop),
    ]
