# Generated by Django 5.1.15 on 2026-09-06，随后按 FILE-004 §4.1.1 核对。
# DDL 清单与规格一致：CreateModel × 2（FileShareLink / FileShareAccess）+
# AddIndex × 3（idx_share_asset_status / idx_share_expires（偏条件，active 态）/
# idx_shareacc_time）。PG 落库走 sqlmigrate + 手工 psql + migrate --fake
#（CLAUDE.md 坑 1——偏条件索引起 SQL 含 WHERE 子句，PG 原生支持，直接整段灌）。

import django.db.models.deletion
import plane.db.models.file_share
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_p2_file_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileShareLink',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('slug', models.CharField(db_index=True, default=plane.db.models.file_share.generate_share_slug, max_length=32, unique=True, verbose_name='分享标识')),
                ('permission', models.CharField(choices=[('view', '仅预览'), ('download', '预览+下载')], default='download', max_length=16, verbose_name='权限')),
                ('password_hash', models.CharField(blank=True, max_length=128, verbose_name='密码哈希（Argon2id，空=无密码）')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间（空=永久）')),
                ('status', models.CharField(choices=[('active', '有效'), ('revoked', '已吊销'), ('expired', '已过期'), ('invalidated', '源失效')], db_index=True, default='active', max_length=16)),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='成功访问次数')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='db.fileasset', verbose_name='分享文件')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_share_links', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'file_share_links',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileShareAccess',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('action', models.CharField(choices=[('unlock', '解锁'), ('view', '预览'), ('download', '下载'), ('unlock_failed', '密码错误')], max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('success', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='db.filesharelink')),
            ],
            options={
                'db_table': 'file_share_accesses',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='filesharelink',
            index=models.Index(fields=['asset', 'status'], name='idx_share_asset_status'),
        ),
        migrations.AddIndex(
            model_name='filesharelink',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['expires_at'], name='idx_share_expires'),
        ),
        migrations.AddIndex(
            model_name='fileshareaccess',
            index=models.Index(fields=['share', 'created_at'], name='idx_shareacc_time'),
        ),
    ]
