# Generated by Django 5.1.15 on 2026-09-06，随后按 GANTT-001 §4.1 核对。
# DDL 清单与规格一致：AddIndex × 1（idx_issue_gantt_viewport——复合偏索引
# (project, start_date, target_date)，偏条件排除软删/归档，服务于甘特视窗相交
# 查询 start_date ≤ viewport_end AND target_date ≥ viewport_start）。
# 零新增表（§4.1「零新增表」）；PG 落库走 sqlmigrate + 手工 psql + migrate
# --fake（CLAUDE.md 坑 1）。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_p2_file_shares'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(condition=models.Q(('archived_at__isnull', True), ('deleted_at__isnull', True)), fields=['project', 'start_date', 'target_date'], name='idx_issue_gantt_viewport'),
        ),
    ]
