# Sprint-5 PROJ-003：ProjectStatusLog + ProjectTemplate 两新表（§4.1 迁移要点 ①②③④）。
# ③ 内置 3 套模板（is_builtin=true, workspace=null）与 ④ 存量项目状态日志首行
# 在数据迁移步骤写入。PG 落库走 sqlmigrate + 手工 psql + migrate --fake（坑 1）。
# Generated by Django 5.1.15 on 2026-09-07 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _seed_builtin_templates(apps, schema_editor):
    ProjectTemplate = apps.get_model("db", "ProjectTemplate")
    BUILTIN = [
        ("基础模板", "空白项目：默认状态四件 + 常用标签",
         [{"name": "待办", "group": "unstarted", "color": "#9CA3AF", "sort_order": 65535.0, "is_default": True},
          {"name": "进行中", "group": "started", "color": "#3B82F6", "sort_order": 131070.0},
          {"name": "已完成", "group": "completed", "color": "#10B981", "sort_order": 196605.0},
          {"name": "已取消", "group": "cancelled", "color": "#6B7280", "sort_order": 262140.0}],
         [{"name": "bug", "color": "#EF4444"}, {"name": "feature", "color": "#3B82F6"},
          {"name": "docs", "color": "#8B5CF6"}],
         [], []),
        ("敏捷研发模板", "Scrum 迭代流：backlog 列 + 研发标签",
         [{"name": "Backlog", "group": "backlog", "color": "#94A3B8", "sort_order": 100.0},
          {"name": "待办", "group": "unstarted", "color": "#9CA3AF", "sort_order": 65535.0, "is_default": True},
          {"name": "进行中", "group": "started", "color": "#3B82F6", "sort_order": 131070.0},
          {"name": "已完成", "group": "completed", "color": "#10B981", "sort_order": 196605.0},
          {"name": "已取消", "group": "cancelled", "color": "#6B7280", "sort_order": 262140.0}],
         [{"name": "frontend", "color": "#22D3EE"}, {"name": "backend", "color": "#A78BFA"},
          {"name": "bug", "color": "#EF4444"}, {"name": "tech-debt", "color": "#F59E0B"}],
         [], []),
        ("产品设计模板", "设计评审流：需求/设计/评审目录 + 交付标签",
         [{"name": "待办", "group": "unstarted", "color": "#9CA3AF", "sort_order": 65535.0, "is_default": True},
          {"name": "设计中", "group": "started", "color": "#3B82F6", "sort_order": 131070.0},
          {"name": "评审中", "group": "started", "color": "#F59E0B", "sort_order": 140000.0},
          {"name": "已完成", "group": "completed", "color": "#10B981", "sort_order": 196605.0}],
         [{"name": "视觉", "color": "#EC4899"}, {"name": "交互", "color": "#06B6D4"},
          {"name": "用研", "color": "#84CC16"}],
         [], [{"name": "需求文档"}, {"name": "设计稿"},
              {"name": "评审记录", "parent_path": "设计稿"}]),
    ]
    for name, desc, states, labels, fields, folders in BUILTIN:
        ProjectTemplate.objects.get_or_create(
            is_builtin=True, name=name,
            defaults={"description": desc, "workspace": None,
                      "states_snapshot": states, "labels_snapshot": labels,
                      "fields_snapshot": fields, "folders_snapshot": folders})


def _backfill_status_logs(apps, schema_editor):
    Project = apps.get_model("db", "Project")
    StatusLog = apps.get_model("db", "ProjectStatusLog")
    for pid, status in Project.objects.all().values_list("id", "status"):
        StatusLog.objects.get_or_create(
            project_id=pid, from_status="", to_status=status, operator=None,
            defaults={"meta": {}})


def _unseed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_s5_access_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatusLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('from_status', models.CharField(max_length=16, verbose_name='源状态')),
                ('to_status', models.CharField(max_length=16, verbose_name='目标状态')),
                ('reason', models.CharField(blank=True, default='', max_length=512, verbose_name='原因')),
                ('meta', models.JSONField(default=dict, verbose_name='扩展')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='db.project', verbose_name='项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '项目状态日志',
                'db_table': 'project_status_logs',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['project', '-created_at'], name='idx_projstatuslog_time')],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='模板名')),
                ('description', models.CharField(blank=True, default='', max_length=512, verbose_name='描述')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='内置模板')),
                ('states_snapshot', models.JSONField(verbose_name='状态快照')),
                ('labels_snapshot', models.JSONField(default=list, verbose_name='标签快照')),
                ('fields_snapshot', models.JSONField(default=list, verbose_name='字段快照')),
                ('folders_snapshot', models.JSONField(default=list, verbose_name='目录快照')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to='db.workspace', verbose_name='工作空间')),
            ],
            options={
                'verbose_name': '项目模板',
                'db_table': 'project_templates',
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_builtin', False)), fields=('workspace', 'name'), name='uniq_projtpl_ws_name')],
            },
        ),
    migrations.RunPython(_seed_builtin_templates, _unseed),
        migrations.RunPython(_backfill_status_logs, _unseed),
    ]
