# Generated by Django 5.1.15 on 2026-09-07 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_s5_team_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationInstallation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('provider', models.CharField(choices=[('github', 'GitHub')], default='github', max_length=16, verbose_name='集成提供方')),
                ('installation_id', models.BigIntegerField(db_index=True, verbose_name='GitHub installation id')),
                ('repository_full_name', models.CharField(help_text='owner/repo，小写', max_length=200, verbose_name='仓库全名')),
                ('repository_node_id', models.CharField(blank=True, default='', max_length=64, verbose_name='仓库 node_id')),
                ('webhook_secret', models.TextField(verbose_name='Webhook 验签密钥（Fernet 密文；HMAC 用 Service 层解密原文）')),
                ('sync_status', models.CharField(choices=[('syncing', '同步中'), ('paused', '已暂停'), ('stale', '仓库失效'), ('unbound', '已解绑')], db_index=True, default='syncing', max_length=16, verbose_name='同步状态')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步心跳')),
                ('token_cache', models.JSONField(blank=True, default=dict, verbose_name='installation token 缓存')),
            ],
            options={
                'verbose_name': '集成安装绑定',
                'db_table': 'integration_installations',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncConflictLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('scope', models.CharField(choices=[('title', '标题'), ('description', '描述'), ('state', '状态'), ('comment', '评论')], db_index=True, max_length=16, verbose_name='冲突面')),
                ('direction', models.CharField(choices=[('inbound', '入站'), ('outbound', '出站')], db_index=True, max_length=16, verbose_name='方向')),
                ('winner_side', models.CharField(choices=[('github', 'GitHub'), ('system', '系统')], max_length=8, verbose_name='时间戳裁决胜出方')),
                ('winner_payload', models.JSONField(verbose_name='胜方字段值')),
                ('loser_payload', models.JSONField(verbose_name='败方字段值（覆盖前快照）')),
                ('delivery_id', models.CharField(blank=True, default='', max_length=64, verbose_name='X-GitHub-Delivery 溯源')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='冲突时刻')),
            ],
            options={
                'verbose_name': '同步冲突日志',
                'db_table': 'integration_sync_conflict_logs',
                'ordering': ('-occurred_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='external_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='外部对象 node_id'),
        ),
        migrations.AddField(
            model_name='issue',
            name='external_source',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='外部来源'),
        ),
        migrations.AddField(
            model_name='issue',
            name='github_context',
            field=models.JSONField(blank=True, default=dict, help_text='{"prs": [], "commits": []}（事件驱动增量，展示层直读）', verbose_name='GitHub 聚合'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('external_source__isnull', False)), fields=('project', 'external_source', 'external_id'), name='uniq_external_anchor_per_project'),
        ),
        migrations.AddField(
            model_name='integrationinstallation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='integrationinstallation',
            name='default_issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.issuetype', verbose_name='入站建任务默认类型'),
        ),
        migrations.AddField(
            model_name='integrationinstallation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='db.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='integrationinstallation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='syncconflictlog',
            name='binding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_logs', to='db.integrationinstallation', verbose_name='绑定'),
        ),
        migrations.AddField(
            model_name='syncconflictlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='syncconflictlog',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_conflict_logs', to='db.issue', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='syncconflictlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddIndex(
            model_name='integrationinstallation',
            index=models.Index(fields=['installation_id', 'repository_full_name'], name='idx_install_repo'),
        ),
        migrations.AddConstraint(
            model_name='integrationinstallation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'repository_full_name'), name='uniq_binding_project_repo_active'),
        ),
        migrations.AddConstraint(
            model_name='integrationinstallation',
            constraint=models.CheckConstraint(condition=models.Q(('repository_full_name', ''), _negated=True), name='chk_repo_name'),
        ),
        migrations.AddIndex(
            model_name='syncconflictlog',
            index=models.Index(fields=['binding', '-occurred_at'], name='idx_conflict_binding_time'),
        ),
        migrations.AddIndex(
            model_name='syncconflictlog',
            index=models.Index(fields=['issue', '-occurred_at'], name='idx_conflict_issue_time'),
        ),
    ]
