# Generated by Django 5.1.15 on 2026-09-07 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_s5_integrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('url', models.URLField(max_length=2048, verbose_name='回调地址')),
                ('secret_encrypted', models.TextField(verbose_name='secret（Fernet 密文）')),
                ('events', models.JSONField(default=list, help_text='§2.3 十二事件闭集子集（webhook.ping 免勾选）', verbose_name='订阅事件面')),
                ('is_active', models.CharField(choices=[('active', '启用'), ('disabled', '手动停用'), ('auto_disabled', '自动停用')], db_index=True, default='active', max_length=16, verbose_name='端点状态')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='终态连败计数')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='db.project', verbose_name='项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='db.workspace', verbose_name='工作空间')),
            ],
            options={
                'verbose_name': 'Webhook 端点',
                'db_table': 'webhook_endpoints',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('event', models.CharField(max_length=64, verbose_name='事件名')),
                ('event_id', models.UUIDField(default=uuid.uuid4, verbose_name='事件去重锚')),
                ('payload', models.JSONField(verbose_name='冻结载荷（重放原样重发）')),
                ('status', models.CharField(choices=[('pending', '待投递'), ('success', '成功'), ('retrying', '退避中'), ('dead', '死信'), ('cancelled', '已终止')], default='pending', max_length=16, verbose_name='投递状态')),
                ('attempts', models.JSONField(default=list, verbose_name='尝试明细')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='下次重试时刻')),
                ('replay_of', models.UUIDField(blank=True, null=True, verbose_name='重放来源 dead 行')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='db.webhookendpoint', verbose_name='端点')),
            ],
            options={
                'verbose_name': 'Webhook 投递',
                'db_table': 'webhook_deliveries',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['project', 'is_active'], name='idx_webhook_fanout'),
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'url'), name='uniq_webhook_project_url'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', '-created_at'], name='idx_delivery_endpoint_time'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(condition=models.Q(('status', 'retrying')), fields=['status', 'next_retry_at'], name='idx_delivery_retry_scan'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(condition=models.Q(('status', 'dead')), fields=['endpoint', 'status'], name='idx_delivery_dead'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('replay_of__isnull', True)), fields=('endpoint', 'event_id'), name='uniq_delivery_endpoint_event'),
        ),
    ]
