# Generated by Django 5.1.15 on 2026-09-07 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_s5_webhooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('kind', models.CharField(choices=[('daily', '每日全量'), ('manual', '手动'), ('drill', '恢复演练')], default='daily', max_length=8, verbose_name='类型')),
                ('status', models.CharField(choices=[('running', '进行中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='running', max_length=8, verbose_name='状态')),
                ('started_at', models.DateTimeField(verbose_name='开始时刻')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时刻')),
                ('dump_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='产物大小')),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA-256')),
                ('object_key', models.TextField(blank=True, default='', verbose_name='MinIO 对象键')),
                ('drill_report', models.JSONField(blank=True, default=dict, help_text='{rto_seconds, smoke_passed, smoke_total, notes}', verbose_name='演练报告')),
                ('error', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '备份执行记录',
                'db_table': 'backup_runs',
                'ordering': ('-started_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['status', '-started_at'], name='idx_backup_recent')],
            },
        ),
    ]
