# Generated by Django 5.1.15 on 2026-09-07 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_s6_backup_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileasset',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='db.workspace', verbose_name='所属工作空间'),
        ),
    ]
