# Generated by Django 5.1.15 on 2026-09-07 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_s6_file_asset_workspace_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseGate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=32, verbose_name='语义化版本')),
                ('commit_sha', models.CharField(max_length=40, verbose_name='提交哈希')),
                ('gate_defects', models.CharField(choices=[('pending', '未开始'), ('running', '进行中'), ('passed', '通过'), ('blocked', '阻塞')], default='pending', max_length=16, verbose_name='缺陷门禁')),
                ('gate_perf', models.CharField(choices=[('pending', '未开始'), ('running', '进行中'), ('passed', '通过'), ('blocked', '阻塞')], default='pending', max_length=16, verbose_name='压测门禁')),
                ('gate_security', models.CharField(choices=[('pending', '未开始'), ('running', '进行中'), ('passed', '通过'), ('blocked', '阻塞')], default='pending', max_length=16, verbose_name='安全门禁')),
                ('gate_compat', models.CharField(choices=[('pending', '未开始'), ('running', '进行中'), ('passed', '通过'), ('blocked', '阻塞')], default='pending', max_length=16, verbose_name='兼容门禁')),
                ('artifacts', models.JSONField(blank=True, default=dict, verbose_name='门禁产物指针')),
                ('checklist', models.JSONField(blank=True, default=list, help_text='[{key, signed_by, signed_at, note, revoked?}]', verbose_name='签署快照')),
                ('verdict', models.CharField(choices=[('none', '未裁决'), ('approved', '放行'), ('rejected', '打回')], default='none', max_length=16, verbose_name='评审裁决')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '发布门禁',
                'db_table': 'release_gates',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseGateEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=32, verbose_name='事件类型')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='载荷')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='事件时刻')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_gate_events', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db.releasegate', verbose_name='发布尝试')),
            ],
            options={
                'verbose_name': '发布门禁事件',
                'db_table': 'release_gate_events',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='releasegate',
            constraint=models.UniqueConstraint(fields=('version', 'commit_sha'), name='uniq_release_gate'),
        ),
        migrations.AddIndex(
            model_name='releasegateevent',
            index=models.Index(fields=['gate', 'id'], name='idx_gate_event'),
        ),
    ]
