# Generated by Django 5.1.15 on 2026-09-08 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_s6_release_gates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='审批流名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用中')),
                ('forbid_self_approve', models.BooleanField(default=True, verbose_name='禁止自审（BR-12）')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flows', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '审批流定义',
                'verbose_name_plural': '审批流定义',
                'db_table': 'approval_flows',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('flow_snapshot', models.JSONField(verbose_name='立案时刻的流+节点定义快照')),
                ('current_level', models.PositiveSmallIntegerField(default=1, verbose_name='当前级')),
                ('status', models.CharField(choices=[('pending', '审批中'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回'), ('terminated', '已终止')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('is_terminal_passed', models.BooleanField(default=False, help_text='终审回填三文档时序闭环（WF-001 §4.4 / WF-002 §4.5 / WF-006 §4.2）：终级票据全通过后、引擎 transition() 回调前置 True——守门放行「is_terminal_passed=True AND status=pending」形态；迁移成功 finalize APPROVED / 守卫失败复位 False 并 finalize TERMINATED(guard_failed_at_complete)。回调窗口外恒 False', verbose_name='终审回填瞬态位')),
                ('terminal_reason', models.CharField(blank=True, default='', help_text='terminated 时：state_changed|guard_failed_at_complete|issue_deleted|issue_archived|admin', max_length=32, verbose_name='终止原因')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完结时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.state', verbose_name='发起前状态（驳回回退语义锚点）')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('issue', models.ForeignKey(help_text='PROTECT：硬删任务前须先终止/归档其实例；软删（deleted_at）不涉级联，实例由 §2.3 钩子终止', on_delete=django.db.models.deletion.PROTECT, related_name='approval_instances', to='db.issue', verbose_name='任务')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '审批实例',
                'verbose_name_plural': '审批实例',
                'db_table': 'approval_instances',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('level', models.PositiveSmallIntegerField(verbose_name='级号（1..10，流内连续递增）')),
                ('pass_mode', models.CharField(choices=[('any', '或签'), ('all', '会签')], max_length=8, verbose_name='通过模式')),
                ('approver_type', models.CharField(choices=[('users', '指定成员'), ('role', '项目角色组'), ('field', '任务字段')], max_length=8, verbose_name='审批人来源')),
                ('approver_config', models.JSONField(default=dict, help_text='users: {"user_ids":[…]}；role: {"role":"PROJ_ADMIN"}；field: {"field":"reporter|assignees"}', verbose_name='审批人配置')),
                ('timeout_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='超时小时（NULL=不超时）')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='db.approvalflow', verbose_name='所属审批流')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'db_table': 'approval_nodes',
                'ordering': ('level',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(verbose_name='级号')),
                ('action', models.CharField(choices=[('pending', '待审'), ('approve', '通过'), ('reject', '驳回'), ('skipped', '跳过（自审/离职）')], default='pending', max_length=8, verbose_name='动作')),
                ('comment', models.TextField(blank=True, default='', verbose_name='意见')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='动作时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='开票时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='db.approvalinstance', verbose_name='所属实例')),
            ],
            options={
                'verbose_name': '审批票',
                'verbose_name_plural': '审批票',
                'db_table': 'approval_records',
                'ordering': ('level', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='工作流名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('version', models.PositiveIntegerField(default=1, help_text='每次发布 +1', verbose_name='版本号')),
                ('based_on_version', models.PositiveIntegerField(blank=True, help_text='基于已发布版本克隆草稿时写入其 version；首次建草稿 NULL（WF-001 §4.8⑤ 注）', null=True, verbose_name='克隆来源版本')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='最近发布时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue_type', models.ForeignKey(blank=True, help_text='NULL = 项目默认工作流', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='db.issuetype', verbose_name='绑定任务类型')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='db.project', verbose_name='所属项目')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '工作流',
                'verbose_name_plural': '工作流',
                'db_table': 'workflows',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('is_initial', models.BooleanField(default=False, verbose_name='是否初始状态')),
                ('layout_x', models.FloatField(default=0.0, verbose_name='画布 X')),
                ('layout_y', models.FloatField(default=0.0, verbose_name='画布 Y')),
                ('field_locks', models.JSONField(blank=True, default=list, help_text='WF-004 协议：[{"field": "target_date"}, {"field": "cf_<key>（TASK-008 field_key 语义名形态）"}]', verbose_name='进入本状态锁定的字段')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('state', models.ForeignKey(help_text='PROTECT：BR-15 被引用状态禁止删除', on_delete=django.db.models.deletion.PROTECT, related_name='workflow_nodes', to='db.state', verbose_name='引用状态')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wf_states', to='db.workflow', verbose_name='所属工作流')),
            ],
            options={
                'verbose_name': '工作流状态节点',
                'verbose_name_plural': '工作流状态节点',
                'db_table': 'workflow_states',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='模板名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='模板版本（发布递增）')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='预设模板')),
                ('graph_snapshot', models.JSONField(help_text='WF-005 §2.1 序列化协议；BR-02 保存即校验', verbose_name='图快照')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='db.workspace', verbose_name='所属工作空间')),
            ],
            options={
                'verbose_name': '工作流模板',
                'verbose_name_plural': '工作流模板',
                'db_table': 'workflow_templates',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='WF-005 模板实例化溯源', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='db.workflowtemplate', verbose_name='来源模板'),
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(help_text='按钮文案，如「提交评审」', max_length=64, verbose_name='流转名称')),
                ('guards', models.JSONField(blank=True, default=list, help_text='schema 见 WF-001 §4.7，守卫矩阵见 WF-004', verbose_name='守卫协议')),
                ('side_effects', models.JSONField(blank=True, default=list, help_text='schema 见 WF-001 §4.7，规则引擎见 WF-003', verbose_name='副作用协议')),
                ('sort_order', models.PositiveIntegerField(default=1000, verbose_name='按钮排序')),
                ('approval_flow', models.ForeignKey(blank=True, help_text='WF-002：非空则流转挂起待审批', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='db.approvalflow', verbose_name='触发审批流')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='db.workflowstate', verbose_name='源节点')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='db.workflowstate', verbose_name='目标节点')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='db.workflow', verbose_name='所属工作流')),
            ],
            options={
                'verbose_name': '流转边',
                'verbose_name_plural': '流转边',
                'db_table': 'workflow_transitions',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='db.workflowtransition', verbose_name='经由此边'),
        ),
        migrations.AddConstraint(
            model_name='approvalflow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name'), name='uniq_approval_flow_name'),
        ),
        migrations.AddConstraint(
            model_name='approvalnode',
            constraint=models.UniqueConstraint(fields=('flow', 'level'), name='uniq_node_level_per_flow'),
        ),
        migrations.AddConstraint(
            model_name='approvalnode',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 10)), name='chk_node_level_range'),
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['approver', 'action', 'created_at'], name='idx_record_todo'),
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['instance', 'level'], name='idx_record_instance'),
        ),
        migrations.AddConstraint(
            model_name='approvalrecord',
            constraint=models.UniqueConstraint(fields=('instance', 'level', 'approver'), name='uniq_record_per_approver'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('workflow', 'state'), name='uniq_state_per_workflow'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['workspace', 'status'], name='idx_template_ws'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.UniqueConstraint(fields=('workspace', 'name', 'version'), name='uniq_template_name_version'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['project', 'status'], name='idx_workflow_project_status'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'published')), fields=('project', 'issue_type'), name='uniq_published_workflow_per_type'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'draft')), fields=('project', 'issue_type'), name='uniq_draft_workflow_per_type'),
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['workflow', 'from_state'], name='idx_transition_from'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(fields=('workflow', 'from_state', 'to_state', 'name'), name='uniq_transition_edge_name'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_state', models.F('to_state')), _negated=True), name='chk_transition_no_self_loop'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['issue', 'status'], name='idx_instance_issue'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['status', 'updated_at'], name='idx_instance_scan'),
        ),
        migrations.AddConstraint(
            model_name='approvalinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('issue', 'transition'), name='uniq_pending_instance_per_edge'),
        ),
    ]
