# Generated by Django 5.1.15 on 2026-09-08 07:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_s7_workflows_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='TASK-013 审批通过锁定（BR-06）'),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='规则名称')),
                ('trigger', models.JSONField(help_text='{"type": "state_changed|issue_created|due_approaching|field_changed", "config": {…}}', verbose_name='触发器')),
                ('conditions', models.JSONField(default=list, help_text='条件数 ≤ 20（继承 TASK-011 冻结，§2.7）', verbose_name='条件（AND 组合，FilterCompiler 子集）')),
                ('actions', models.JSONField(help_text='复用 WF-001 §4.7 动作协议 + transition/add_label', verbose_name='动作（1..5 个，顺序执行）')),
                ('dedup_window_minutes', models.PositiveIntegerField(default=60, verbose_name='去重窗口（BR-09）')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='BR-13 连续失败熔断计数')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '自动化规则',
                'verbose_name_plural': '自动化规则',
                'db_table': 'automation_rules',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.JSONField(verbose_name='事件快照（type/payload/origin/chain_depth）')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], max_length=8, verbose_name='状态')),
                ('skip_reason', models.CharField(blank=True, default='', help_text='dedup|origin|chain_depth', max_length=32, verbose_name='跳过原因')),
                ('action_results', models.JSONField(default=list, verbose_name='动作明细（[{"type":"assign","ok":true,"detail":{…}}, …]）')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='执行耗时（毫秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.issue', verbose_name='任务')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='db.automationrule', verbose_name='规则')),
            ],
            options={
                'verbose_name': '自动化执行日志',
                'verbose_name_plural': '自动化执行日志',
                'db_table': 'automation_runs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AutomationSetting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('allow_rule_chain', models.BooleanField(default=False, verbose_name='允许规则级联触发（默认关）')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation_setting', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '自动化设置',
                'verbose_name_plural': '自动化设置',
                'db_table': 'automation_settings',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectWorklogConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('approval_enabled', models.BooleanField(default=True, verbose_name='启用周审批')),
                ('daily_soft_limit_minutes', models.PositiveIntegerField(default=480, verbose_name='单日软上限（分钟，超出仅警告，BR-08）')),
                ('granularity_minutes', models.PositiveSmallIntegerField(choices=[(15, '15 分钟'), (30, '30 分钟'), (60, '60 分钟')], default=15, verbose_name='单笔填报粒度（分钟，BR-08）')),
                ('warn_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.80'), max_digits=3, verbose_name='任务超额预警阈值（BR-10）')),
                ('weekly_capacity_minutes', models.PositiveIntegerField(default=2400, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(3600)], verbose_name='周容量（分钟，30-60h 可配——负载°分母唯一配置源）')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_config', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '工时项目配置',
                'verbose_name_plural': '工时项目配置',
                'db_table': 'project_worklog_configs',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkLogApproval',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('week_start', models.DateField(verbose_name='周起始日（周一）')),
                ('status', models.CharField(choices=[('draft', '待提交'), ('submitted', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('review_note', models.CharField(blank=True, max_length=500, verbose_name='审批意见（驳回/撤销必填，BR-05/07）')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='最近提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='最近审批时间')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_approvals', to=settings.AUTH_USER_MODEL, verbose_name='被审人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_approvals', to='db.project', verbose_name='所属项目')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_worklog_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '工时审批批次',
                'verbose_name_plural': '工时审批批次',
                'db_table': 'worklog_approvals',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkLogSummary',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('week_start', models.DateField(verbose_name='周起始日')),
                ('total_minutes', models.PositiveIntegerField(default=0, verbose_name='总工时（分钟）')),
                ('task_count', models.PositiveIntegerField(default=0, verbose_name='涉及任务数')),
                ('approved_minutes', models.PositiveIntegerField(default=0, verbose_name='已审批工时')),
                ('over_8h_days', models.PositiveIntegerField(default=0, verbose_name='单日超 480 分钟的天数（BR-11，refresh 时日级聚合派生）')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='是否冻结（批次通过）')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_summaries', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_summaries', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '工时聚合快照',
                'verbose_name_plural': '工时聚合快照',
                'db_table': 'worklog_summaries',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['project', 'is_active'], name='idx_rule_active'),
        ),
        migrations.AddConstraint(
            model_name='automationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name'), name='uniq_rule_name_per_project'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['rule', 'created_at'], name='idx_run_rule'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['created_at'], name='idx_run_retention'),
        ),
        migrations.AddConstraint(
            model_name='projectworklogconfig',
            constraint=models.CheckConstraint(condition=models.Q(('warn_ratio__gte', Decimal('0.5')), ('warn_ratio__lte', Decimal('1.5'))), name='chk_worklog_warn_ratio_range'),
        ),
        migrations.AddConstraint(
            model_name='projectworklogconfig',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_capacity_minutes__gte', 1800), ('weekly_capacity_minutes__lte', 3600)), name='chk_worklog_weekly_capacity_range'),
        ),
        migrations.AddIndex(
            model_name='worklogapproval',
            index=models.Index(fields=['project', 'week_start', 'status'], name='idx_wla_project_week'),
        ),
        migrations.AddConstraint(
            model_name='worklogapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('actor', 'project', 'week_start'), name='uniq_worklog_approval_batch'),
        ),
        migrations.AddIndex(
            model_name='worklogsummary',
            index=models.Index(fields=['project', 'week_start'], name='idx_wls_project_week'),
        ),
        migrations.AddIndex(
            model_name='worklogsummary',
            index=models.Index(fields=['actor', 'week_start'], name='idx_wls_actor_week'),
        ),
        migrations.AddConstraint(
            model_name='worklogsummary',
            constraint=models.UniqueConstraint(fields=('project', 'actor', 'week_start'), name='uniq_worklog_summary_cell'),
        ),
    ]
