# Generated by Django 5.1.15 on 2026-09-08 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_s7_r3_automations_worklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDistribution',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('template_version', models.PositiveIntegerField(verbose_name='下发时模板版本')),
                ('locked', models.BooleanField(default=False, verbose_name='锁定')),
                ('status', models.CharField(db_index=True, default='pending_confirm', help_text='pending_confirm|active|upgrade_available|withdrawn|unlocked', max_length=16, verbose_name='状态')),
                ('state_mapping', models.JSONField(default=dict, verbose_name='状态映射单留痕（BR-05）')),
                ('applied_workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.workflow', verbose_name='实例化产物')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_distributions', to='db.project', verbose_name='项目')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='db.workflowtemplate', verbose_name='模板')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '模板下发记录',
                'verbose_name_plural': '模板下发记录',
                'db_table': 'template_distributions',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateUnlockRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('kind', models.CharField(choices=[('unlock', '解锁（转独立副本）'), ('upgrade', '升级（替换式升级到新版本）')], max_length=8, verbose_name='申请类型')),
                ('reason', models.CharField(max_length=255, verbose_name='申请理由（必填）')),
                ('status', models.CharField(choices=[('pending', '待审'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=8, verbose_name='状态')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to='db.templatedistribution', verbose_name='下发记录')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='处理人（WS_ADMIN）')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_unlock_requests', to='db.project', verbose_name='项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '模板解锁/升级申请',
                'verbose_name_plural': '模板解锁/升级申请',
                'db_table': 'template_unlock_requests',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalAuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32, verbose_name='事件类型（§2.1 清单）')),
                ('payload', models.JSONField(default=dict, verbose_name='载荷（含 comment_sha256，BR-04）')),
                ('request_id', models.CharField(blank=True, default='', max_length=32, verbose_name='请求追踪（BR-09）')),
                ('prev_hash', models.CharField(max_length=64, verbose_name='链上前事件哈希')),
                ('event_hash', models.CharField(max_length=64, verbose_name='本事件哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('actor', models.ForeignKey(help_text='NULL=系统（超时/跳票/归档）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.approvalinstance', verbose_name='审批实例')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.project')),
            ],
            options={
                'verbose_name': '审批审计事件',
                'verbose_name_plural': '审批审计事件',
                'db_table': 'approval_audit_events',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['project', 'created_at'], name='idx_aae_project_time'), models.Index(fields=['project', 'actor', 'created_at'], name='idx_aae_actor'), models.Index(fields=['instance'], name='idx_aae_instance'), models.Index(fields=['created_at'], name='idx_aae_retention')],
            },
        ),
        migrations.AddConstraint(
            model_name='templatedistribution',
            constraint=models.UniqueConstraint(fields=('template', 'project'), name='uniq_distribution'),
        ),
        migrations.AddIndex(
            model_name='templateunlockrequest',
            index=models.Index(fields=['project', 'status'], name='idx_unlock_req_proj'),
        ),
        migrations.AddConstraint(
            model_name='templateunlockrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'pending')), fields=('project',), name='uniq_unlock_request_pending_per_project'),
        ),
    ]
