# Generated by Django 5.1.15 on 2026-09-08 23:18

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_s7_r5_templates_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalauditevent',
            name='created_at',
            field=models.DateTimeField(verbose_name='时间'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField(db_index=True, editable=False)),
                ('sort_order', models.FloatField(default=65536.0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='db.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='db.workspace')),
            ],
            options={
                'db_table': 'department',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='db.department'),
        ),
        migrations.CreateModel(
            name='DepartmentGrantBatch',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('department_id_snapshot', models.UUIDField(editable=False)),
                ('role', models.IntegerField(choices=[(20, 'Admin'), (15, 'Contributor'), (10, 'Commenter'), (5, 'Viewer')], default=15)),
                ('with_descendants', models.BooleanField(default=True)),
                ('added_count', models.IntegerField(default=0)),
                ('role_changed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('unchanged_count', models.IntegerField(default=0)),
                ('member_snapshot', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_batches', to='db.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'department_grant_batch',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(models.F('workspace'), models.F('parent'), models.F('sort_order'), name='idx_department_tree_read'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(models.F('workspace'), models.F('parent'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='uq_department_sibling_name'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(models.F('workspace'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), name='uq_department_root_name'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gt', 0)), name='ck_department_sort_positive'),
        ),
        migrations.AddIndex(
            model_name='departmentgrantbatch',
            index=models.Index(models.F('project'), models.F('created_at'), name='idx_grant_batch_project'),
        ),
    ]
