# Generated by Django 5.1.15 on 2026-09-09 00:47

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_s8_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('permissions', models.JSONField(default=list)),
                ('is_builtin_template', models.BooleanField(default=False)),
                ('template_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='db.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'custom_role',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRoleAssignment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('grant_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.departmentgrantbatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='db.customrole')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_role_assignment',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='customrole',
            index=models.Index(models.F('project'), models.F('deleted_at'), name='idx_custom_role_project'),
        ),
        migrations.AddConstraint(
            model_name='customrole',
            constraint=models.UniqueConstraint(models.F('project'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='uq_custom_role_name'),
        ),
        migrations.AddConstraint(
            model_name='customrole',
            constraint=models.CheckConstraint(condition=models.Q(('permissions__isnull', False)), name='ck_custom_role_perms_shape'),
        ),
        migrations.AddIndex(
            model_name='projectroleassignment',
            index=models.Index(models.F('project'), models.F('user'), name='idx_role_assign_lookup'),
        ),
        migrations.AddConstraint(
            model_name='projectroleassignment',
            constraint=models.UniqueConstraint(models.F('project'), models.F('user'), models.F('role'), condition=models.Q(('deleted_at__isnull', True)), name='uq_role_assignment'),
        ),
    ]
