# Generated by Django 5.1.15 on 2026-09-09 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_s8_grant_batch_target_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol', models.CharField(choices=[('oidc', 'OIDC'), ('saml', 'SAML')], max_length=8)),
                ('is_enabled', models.BooleanField(default=False)),
                ('issuer', models.URLField(blank=True)),
                ('client_id', models.CharField(blank=True, max_length=200)),
                ('client_secret_enc', models.BinaryField(null=True)),
                ('jwks_url', models.URLField(blank=True)),
                ('idp_entity_id', models.CharField(blank=True, max_length=300)),
                ('idp_sso_url', models.URLField(blank=True)),
                ('idp_slo_url', models.URLField(blank=True)),
                ('idp_x509_cert', models.TextField(blank=True)),
                ('sp_entity_id', models.CharField(blank=True, max_length=300)),
                ('sp_private_key_enc', models.BinaryField(null=True)),
                ('sp_x509_cert', models.TextField(blank=True)),
                ('claim_department', models.CharField(blank=True, default='department', max_length=64)),
                ('claim_role', models.CharField(blank=True, default='groups', max_length=64)),
                ('jit_default_role', models.CharField(default='WS_MEMBER', max_length=20)),
                ('sync_profile_on_login', models.BooleanField(default=True)),
                ('enforce_sso', models.BooleanField(default=False)),
                ('last_test_passed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_idps', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_provider', to='db.workspace')),
            ],
            options={
                'db_table': 'identity_provider',
            },
        ),
        migrations.CreateModel(
            name='SSOAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('email_at_binding', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='db.identityprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sso_account',
                'indexes': [models.Index(models.F('user'), name='idx_sso_account_user')],
                'constraints': [models.UniqueConstraint(models.F('idp'), models.F('subject'), name='uq_sso_subject')],
            },
        ),
    ]
