# Generated by Django 5.1.15 on 2026-09-09 01:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_s8_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=24)),
                ('action', models.CharField(max_length=48)),
                ('actor_id', models.CharField(max_length=64, null=True)),
                ('actor_snapshot', models.JSONField(default=dict)),
                ('object_type', models.CharField(max_length=32, null=True)),
                ('object_id', models.CharField(max_length=64, null=True)),
                ('object_snapshot', models.JSONField(default=dict)),
                ('detail', models.JSONField(default=dict)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserViewPreference',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('pinned', models.BooleanField(default=True, verbose_name='订阅（侧栏展示）')),
                ('sort_order', models.FloatField(default=65535.0, verbose_name='个人订阅排序（BR-11）')),
            ],
            options={
                'verbose_name': '用户视图偏好',
                'verbose_name_plural': '用户视图偏好',
                'db_table': 'user_view_preferences',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issueview',
            name='is_project_default',
            field=models.BooleanField(default=False, help_text='每项目至多 1 个（BR-04）；仅锁定视图可设（BR-05）', verbose_name='项目默认视图（新成员自动订阅）'),
        ),
        migrations.AddField(
            model_name='issueview',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='锁定时间'),
        ),
        migrations.AddField(
            model_name='issueview',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_views', to=settings.AUTH_USER_MODEL, verbose_name='锁定人'),
        ),
        migrations.AddConstraint(
            model_name='issueview',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_project_default', True)), fields=('project',), name='uq_view_project_default'),
        ),
        migrations.AddConstraint(
            model_name='issueview',
            constraint=models.CheckConstraint(condition=models.Q(('is_project_default', False), ('is_locked', True), _connector='OR'), name='ck_view_project_default_locked'),
        ),
        migrations.AddField(
            model_name='userviewpreference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='userviewpreference',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_preferences', to='db.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='userviewpreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='userviewpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userviewpreference',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='db.issueview', verbose_name='视图'),
        ),
        migrations.AddIndex(
            model_name='userviewpreference',
            index=models.Index(fields=['user', 'project', 'pinned'], name='idx_view_pref_user_proj'),
        ),
        migrations.AddIndex(
            model_name='userviewpreference',
            index=models.Index(fields=['view', 'pinned'], name='idx_view_pref_view'),
        ),
        migrations.AddConstraint(
            model_name='userviewpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'view'), name='uq_view_pref_user_view_alive'),
        ),
    ]
