# Generated by Django 5.1.15 on 2026-09-09 16:30

import django.db.models.deletion
import django.db.models.functions.comparison
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_s8_view_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('depth', models.PositiveSmallIntegerField(default=1, verbose_name='层级（冗余）')),
                ('sort_order', models.FloatField(default=65535.0, verbose_name='排序值')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('manager', models.ForeignKey(blank=True, help_text='BR-03 数据支撑：manager（含祖先节点 manager）与 WS_ADMIN+ 共同持有管理权；NULL 时仅 WS_ADMIN+', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_portfolios', to=settings.AUTH_USER_MODEL, verbose_name='项目集负责人')),
                ('parent', models.ForeignKey(blank=True, help_text='NULL = 根组合', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.portfolio', verbose_name='父节点')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='db.workspace', verbose_name='所属工作空间')),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioMilestone',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='里程碑名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('target_date', models.DateField(db_index=True, verbose_name='截止日期')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='db.portfolio', verbose_name='所属项目集')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'portfolio_milestones',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilestoneItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='权重快照')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_items', to='db.issue', verbose_name='贡献任务')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.portfoliomilestone', verbose_name='里程碑')),
            ],
            options={
                'db_table': 'milestone_items',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounted_projects', to='db.portfolio', verbose_name='项目集')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_mount', to='db.project', verbose_name='项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'portfolio_projects',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['workspace', 'parent'], name='idx_portfolio_ws_parent'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(models.F('workspace'), django.db.models.functions.comparison.Coalesce('parent', models.Value(uuid.UUID('00000000-0000-0000-0000-000000000000'))), models.F('name'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_portfolio_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('depth__gte', 1), ('depth__lte', 3)), name='chk_portfolio_depth'),
        ),
        migrations.AddIndex(
            model_name='portfoliomilestone',
            index=models.Index(fields=['portfolio', 'target_date'], name='idx_pm_portfolio_target'),
        ),
        migrations.AddConstraint(
            model_name='milestoneitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('milestone', 'issue'), name='uniq_milestone_issue'),
        ),
        migrations.AddConstraint(
            model_name='portfolioproject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project',), name='uniq_project_single_portfolio'),
        ),
    ]
