# Generated by Django 5.1.15 on 2026-09-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_s9_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('issue.assigned', '被指派'), ('issue.mentioned', '被提及'), ('issue.commented', '任务被评论'), ('issue.updated', '任务被更新'), ('comment.replied', '评论被回复'), ('milestone.at_risk', '里程碑延期风险')], db_index=True, max_length=32, verbose_name='事件类型'),
        ),
    ]
