# Generated by Django 5.1.15 on 2026-09-09 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_s9_notification_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='迭代名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('planned', '规划中'), ('active', '进行中'), ('completed', '已完成')], db_index=True, default='planned', max_length=16, verbose_name='状态')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'cycles',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='db.cycle', verbose_name='所属迭代'),
        ),
        migrations.CreateModel(
            name='CycleSnapshot',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('snapshot_date', models.DateField(verbose_name='快照日期')),
                ('measure', models.CharField(help_text='count/estimate_minutes/cf_<uuid>', max_length=32, verbose_name='度量口径')),
                ('remaining_total', models.FloatField(help_text='未达 completed 且未 cancelled 组的度量总和（cancelled 不计剩余）', verbose_name='剩余总量')),
                ('remaining_by_group', models.JSONField(help_text='{"backlog": 0, "unstarted": 12, "started": 8.5, "completed": 30, "cancelled": 0}', verbose_name='按组分解')),
                ('completed_delta', models.FloatField(default=0, help_text='当日新进入 completed 的度量 − 当日流出 completed 的度量（重开为负项）；不含 scope change', verbose_name='当日净完成量')),
                ('scope_delta', models.FloatField(default=0, help_text='cycles 事件加入 +x / 移出 -x 的度量净额（展示口径，BR-09 ▲▼），不参与恒等式对账', verbose_name='当日 scope change 净额')),
                ('cancelled_net_delta', models.FloatField(default=0, help_text='转入 − 回流净口径；cancelled 不计剩余，不得并入展示 delta（恒等式修正项）', verbose_name='当日净转入 cancelled 量')),
                ('scope_remaining_delta', models.FloatField(default=0, help_text='cycles 事件按任务当日所处组是否计入剩余折算（恒等式修正项）', verbose_name='scope change 计剩余折算净额')),
                ('adjustment_delta', models.FloatField(default=0, help_text='estimate_minutes 编辑净差（仅计剩余组）+ 任务删除的剩余修正（恒等式修正项）', verbose_name='估算编辑/任务删除修正量')),
                ('scope_events', models.JSONField(blank=True, default=list, help_text='complete 时序列化进终版快照（BR-06 归档不可篡改）；日快照恒为空', verbose_name='scope 事件清单')),
                ('scope_total', models.FloatField(default=0, help_text='迭代内全部任务度量合计（不含 cancelled）；首日快照即速率图 planned（BR-10）', verbose_name='迭代范围总量')),
                ('frozen', models.BooleanField(default=False, verbose_name='是否冻结（迭代结束）')),
                ('is_final', models.BooleanField(default=False, help_text='complete 时落一行 is_final=true（BR-04），速率统计唯一锚', verbose_name='终版快照')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='db.cycle', verbose_name='迭代')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'cycle_snapshots',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyGroupSnapshot',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('snapshot_date', models.DateField(verbose_name='快照日期')),
                ('measure', models.CharField(max_length=32, verbose_name='度量口径')),
                ('counts', models.JSONField(help_text='{"backlog": 42, "unstarted": 18, "started": 9, "completed": 130, "cancelled": 6}', verbose_name='五组数量/度量')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_group_snapshots', to='db.project', verbose_name='项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'daily_group_snapshots',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectReportConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('report_measure', models.CharField(default='count', help_text='count / estimate_minutes / cf_<uuid>（数字类型自定义字段，BR-07）', max_length=32, verbose_name='报表度量口径')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_config', to='db.project', verbose_name='项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'project_report_configs',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['project', 'status'], name='idx_cycle_project_status'),
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='chk_cycle_date_range'),
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('project',), name='uniq_active_cycle_per_project'),
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name'), name='uniq_cycle_name_per_project'),
        ),
        migrations.AddIndex(
            model_name='cyclesnapshot',
            index=models.Index(fields=['cycle', 'snapshot_date'], name='idx_cs_cycle_day'),
        ),
        migrations.AddConstraint(
            model_name='cyclesnapshot',
            constraint=models.UniqueConstraint(fields=('cycle', 'snapshot_date'), name='uniq_cycle_snapshot_day'),
        ),
        migrations.AddConstraint(
            model_name='cyclesnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_final', True)), fields=('cycle',), name='uniq_cycle_final_snapshot'),
        ),
        migrations.AddIndex(
            model_name='dailygroupsnapshot',
            index=models.Index(fields=['project', 'snapshot_date'], name='idx_dgs_project_day'),
        ),
        migrations.AddConstraint(
            model_name='dailygroupsnapshot',
            constraint=models.UniqueConstraint(fields=('project', 'snapshot_date', 'measure'), name='uniq_dgs_project_day_measure'),
        ),
    ]
