# Generated by Django 5.1.15 on 2026-09-09 17:05

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_s9_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('depth', models.PositiveSmallIntegerField(default=1, verbose_name='层级（冗余）')),
                ('sort_order', models.FloatField(default=65535.0, verbose_name='排序值')),
                ('draft_json', models.JSONField(blank=True, null=True, verbose_name='草稿（覆盖式，BR-04）')),
                ('collab_doc_id', models.UUIDField(blank=True, null=True, verbose_name='P4 协同文档 ID 预留')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除人（回收站过滤，BR-09：非 manager 仅见本人删除项）')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.wikipage', verbose_name='父页面')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'wiki_pages',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WikiPageVersion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号（页内递增）')),
                ('content_json', models.JSONField(verbose_name='Tiptap JSON（编辑源）')),
                ('content_html', models.TextField(verbose_name='渲染态（服务端派生，BR-03）')),
                ('content_text', models.TextField(verbose_name='剥离文本（检索态）')),
                ('change_summary', models.CharField(blank=True, max_length=200, verbose_name='变更摘要')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='db.wikipage', verbose_name='页面')),
                ('rolled_back_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.wikipageversion', verbose_name='回滚溯源')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'wiki_page_versions',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wikipage',
            name='base_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.wikipageversion', verbose_name='草稿基线版本'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.wikipageversion', verbose_name='当前发布版本'),
        ),
        migrations.CreateModel(
            name='WikiSpace',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='空间名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('permission_mode', models.CharField(choices=[('inherit', '继承项目角色'), ('whitelist', '编辑白名单')], default='inherit', max_length=16, verbose_name='权限模式')),
                ('editor_whitelist', models.JSONField(blank=True, default=list, help_text='[{"type": "member", "id": "<uuid>"}, {"type": "department", "id": "<uuid>"}]', verbose_name='编辑白名单')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_spaces', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'wiki_spaces',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wikipage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='db.wikispace', verbose_name='所属空间'),
        ),
        migrations.AddIndex(
            model_name='wikipageversion',
            index=models.Index(fields=['page', '-version_no'], name='idx_wpv_page_version'),
        ),
        migrations.AddIndex(
            model_name='wikipageversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_text'], name='idx_wpv_text_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='wikipageversion',
            constraint=models.UniqueConstraint(fields=('page', 'version_no'), name='uniq_wiki_page_version_no'),
        ),
        migrations.AddConstraint(
            model_name='wikispace',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name'), name='uniq_wiki_space_name'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['space', 'parent'], name='idx_wiki_page_tree'),
        ),
        migrations.AddConstraint(
            model_name='wikipage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('space', 'parent', 'title'), name='uniq_wiki_page_title_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='wikipage',
            constraint=models.CheckConstraint(condition=models.Q(('depth__gte', 1), ('depth__lte', 5)), name='chk_wiki_page_depth'),
        ),
    ]
