# Generated by Django 5.1.15 on 2026-09-09 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_s9_wiki'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPMAlertConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('overdue_alert_enabled', models.BooleanField(default=True, verbose_name='关键逾期预警（BR-08）')),
                ('float_consumed_alert_enabled', models.BooleanField(default=True, verbose_name='浮动耗尽预警（BR-09）')),
                ('target_completion_date', models.DateField(blank=True, null=True, verbose_name='项目目标完工日（BR-06 逆推锚点）')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpm_alert_config', to='db.project', verbose_name='项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'cpm_alert_config',
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('project',), name='uniq_cpm_alert_config_project')],
            },
        ),
        migrations.CreateModel(
            name='IssueCPMCache',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('es', models.DateField(verbose_name='最早开始')),
                ('ef', models.DateField(verbose_name='最早完成')),
                ('ls', models.DateField(verbose_name='最晚开始')),
                ('lf', models.DateField(verbose_name='最晚完成')),
                ('float_days', models.IntegerField(verbose_name='浮动天数')),
                ('is_critical', models.BooleanField(default=False, verbose_name='是否关键')),
                ('has_external_preds', models.BooleanField(default=False, verbose_name='有外部前置（BR-03）')),
                ('input_hash', models.CharField(max_length=32, verbose_name='输入指纹')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='计算时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpm_row', to='db.issue', verbose_name='任务')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpm_cache', to='db.project', verbose_name='项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'issue_cpm_cache',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['project', 'is_critical'], name='idx_cpm_critical')],
                'constraints': [models.UniqueConstraint(fields=('project', 'issue'), name='uniq_cpm_cache_issue')],
            },
        ),
    ]
