# Generated by Django 5.1.15 on 2026-09-09 17:59

import django.db.models.deletion
import plane.db.models.health
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_s9_cpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('weights', models.JSONField(default=plane.db.models.health.default_health_weights, verbose_name='四维权重（和恒为 1，序列化层校验）')),
                ('thresholds', models.JSONField(default=plane.db.models.health.default_health_thresholds, help_text='effort 键为允许偏差半宽（默认 0.20 即 0.8~1.2）', verbose_name='四维参考阈值（维度卡参考线/超标角标，不入评分——BR-02）')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_config', to='db.project', verbose_name='项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'health_configs',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('export_type', models.CharField(help_text='workload_csv / audit_csv / burndown_csv', max_length=32, verbose_name='导出类型')),
                ('params', models.JSONField(default=dict, verbose_name='导出参数（from/to/筛选）')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '进行中'), ('succeeded', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('file_key', models.CharField(blank=True, max_length=256, verbose_name='MinIO 对象键')),
                ('download_url', models.TextField(blank=True, verbose_name='预签名下载 URL（生成时写入）')),
                ('error', models.TextField(blank=True, verbose_name='失败原因')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='URL 过期时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_tasks', to='db.project', verbose_name='项目（可空）')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_tasks', to='db.workspace', verbose_name='工作空间')),
            ],
            options={
                'db_table': 'export_tasks',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', 'status'], name='idx_export_ws_status'), models.Index(fields=['created_by', '-created_at'], name='idx_export_creator')],
            },
        ),
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('snapshot_date', models.DateField(verbose_name='快照日期')),
                ('dimensions', models.JSONField(help_text='{"progress": {"value": -0.07, "score": 86, "n": 128, "drilldown_count": 38}, …}——维度为 null 即样本不足（BR-05）', verbose_name='四维明细')),
                ('total_score', models.FloatField(null=True, verbose_name='总评（null = 数据不足，BR-10）')),
                ('band', models.CharField(help_text='green/yellow/red/insufficient——16 位容纳 insufficient（BR-10）', max_length=16, verbose_name='分档')),
                ('config_snapshot', models.JSONField(verbose_name='阈值权重快照')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='db.project', verbose_name='项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'health_snapshots',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['project', 'snapshot_date'], name='idx_hs_project_day')],
                'constraints': [models.UniqueConstraint(fields=('project', 'snapshot_date'), name='uniq_health_snapshot_day')],
            },
        ),
    ]
