# Generated by Django 5.1.15 on 2026-09-11 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_and_seed(apps, schema_editor):
    """门控回填 + 平台默认种子（AUTH-012 §4.1，BR-11）。

    TENANT_GOVERNANCE_ENABLED=False（私有化）直接返回：存量 Workspace 保持
    tenant=NULL「未治理」语义，audit_log 不回填、不播种子——杜绝私有化实例
    被静默批量建租户。仅 SaaS 形态（True）执行。
    """
    from django.conf import settings

    if not getattr(settings, "TENANT_GOVERNANCE_ENABLED", False):
        return

    Tenant = apps.get_model("db", "Tenant")
    Workspace = apps.get_model("db", "Workspace")
    RiskRule = apps.get_model("db", "RiskRule")

    # 1) 每存活 Workspace 建同名 Tenant 并归集（§4.1 回填，批 500）
    last_pk = None
    while True:
        qs = Workspace.objects.filter(tenant__isnull=True, deleted_at__isnull=True)
        if last_pk is not None:
            qs = qs.filter(id__gt=last_pk)
        batch = list(qs.order_by("id")[:500])
        if not batch:
            break
        for ws in batch:
            tenant = Tenant.objects.create(name=ws.name)
            Workspace.objects.filter(id=ws.id).update(tenant=tenant)
            last_pk = ws.id

    # 2) audit_log.tenant_id 同源映射回填（与 Workspace.tenant 同一门控承载）
    schema_editor.execute(
        "UPDATE audit_log a SET tenant_id = w.tenant_id "
        "FROM workspaces w WHERE a.workspace_id = w.id AND w.tenant_id IS NOT NULL;"
    )

    # 3) RiskRule 平台默认六行（tenant=NULL；§2.4 触发条件列）
    platform_defaults = [
        ("R-01", {"count": 200, "window": "10m"}, "alert"),        # 登录风暴（触发附 IP 段封禁 30min）
        ("R-02", {"distance_km": 1000, "window": "1h"}, "alert"),  # 异地登录（非计数规则）
        ("R-03", {"warn_ratio": 0.8, "deny_ratio": 1.0, "window": "1d"}, "deny"),  # 批量导出（80% 预警/100% 硬拒）
        ("R-04", {"count": 5, "window": "1h"}, "alert"),           # 权限批量提升（主体=操作者）
        ("R-05", {"count": 50, "window": "1d",
                  "night_start_hour": 0, "night_end_hour": 6}, "alert"),           # 深夜批量删除（时段谓词）
        ("R-06", {"quota_ratio": 0.5, "getlist_ratio": 0.95, "window": "1h"}, "throttle"),  # API 爬虫（双键判定）
    ]
    for code, threshold, action in platform_defaults:
        RiskRule.objects.get_or_create(
            code=code, tenant__isnull=True,
            defaults={"threshold": threshold, "action": action})


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_s9_builtin_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemadmin',
            name='is_tenant_ops',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128)),
                ('tier', models.CharField(choices=[('free', '免费'), ('standard', '标准'), ('enterprise', '企业'), ('flagship', '旗舰')], default='free', max_length=12)),
                ('seats', models.PositiveIntegerField(default=10)),
                ('is_frozen', models.BooleanField(default=False)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'gov_tenant',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('rule_code', models.CharField(max_length=8)),
                ('severity', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('open', '待处置'), ('actioned', '已处置'), ('dismissed', '误报关闭')], default='open', max_length=10)),
                ('evidence', models.JSONField()),
                ('aggregate_key', models.CharField(max_length=128)),
                ('actions', models.JSONField(default=list)),
                ('freeze_approval', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='db.tenant')),
            ],
            options={
                'db_table': 'gov_risk_event',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAppeal',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待复核'), ('accepted', '申诉成立'), ('rejected', '申诉驳回')], default='pending', max_length=10)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_appeals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_appeals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='db.riskevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_appeals', to='db.tenant')),
            ],
            options={
                'db_table': 'gov_risk_appeal',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GovernanceTicket',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('scope', models.JSONField()),
                ('approve_channel', models.CharField(choices=[('online', '客户在线批准'), ('written', '书面授权')], max_length=8)),
                ('written_ref', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', '待客户批准'), ('approved', '已批准'), ('rejected', '已驳回'), ('expired', '已过期'), ('revoked', '已撤回')], default='pending', max_length=10)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l2_tickets_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l2_tickets_requested', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('risk_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l2_tickets', to='db.riskevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l2_tickets', to='db.tenant')),
            ],
            options={
                'db_table': 'gov_l2_ticket',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoundaryReport',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('state', models.CharField(choices=[('queued', '排队'), ('processing', '生成中'), ('succeeded', '完成'), ('failed', '失败')], default='queued', max_length=12)),
                ('cross_tenant_hits', models.PositiveIntegerField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_reports', to='db.tenant')),
            ],
            options={
                'db_table': 'gov_boundary_report',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='db.tenant', verbose_name='归属租户'),
        ),
        migrations.CreateModel(
            name='TenantQuota',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('storage_bytes', models.BigIntegerField(blank=True, null=True)),
                ('member_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('api_rate_per_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('export_rows_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('webhook_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('project_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('downgrade_grace_until', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='db.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'gov_tenant_quota',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=8)),
                ('threshold', models.JSONField()),
                ('action', models.CharField(choices=[('alert', '仅告警'), ('throttle', '限流'), ('freeze', '冻结'), ('deny', '硬拒')], default='alert', max_length=12)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.tenant')),
            ],
            options={
                'db_table': 'gov_risk_rule',
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('code',), name='uq_risk_rule_platform'), models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('code', 'tenant'), name='uq_risk_rule_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['tenant', '-created_at'], name='idx_risk_event_tenant'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['status', '-created_at'], name='idx_risk_event_open'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['rule_code', '-created_at'], name='idx_risk_event_rule'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['aggregate_key', '-created_at'], name='idx_risk_event_agg'),
        ),
        migrations.AddIndex(
            model_name='riskappeal',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='idx_risk_appeal_tenant'),
        ),
        migrations.AddIndex(
            model_name='governanceticket',
            index=models.Index(fields=['risk_event', 'status', '-created_at'], name='idx_l2_ticket_event'),
        ),
        migrations.AddIndex(
            model_name='boundaryreport',
            index=models.Index(fields=['tenant', '-created_at'], name='idx_boundary_report_tenant'),
        ),
        # ── audit_log 增补租户列（AUTH-012 §4.1：分区表 managed=False，DDL 经
        #    RunSQL 交付；tenant_id 不建 FK 系 AUTH-010 零外键原则之引申）──
        migrations.RunSQL(
            sql=(
                "ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS tenant_id uuid NULL;\n"
                "CREATE INDEX IF NOT EXISTS idx_audit_tenant ON audit_log (tenant_id, created_at);"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS idx_audit_tenant;\n"
                "ALTER TABLE audit_log DROP COLUMN IF EXISTS tenant_id;"
            ),
        ),
        # ── 门控回填 + 种子（BR-11：TENANT_GOVERNANCE_ENABLED=False 直接返回——
        #    私有化存量保持 tenant=NULL「未治理」语义；仅 SaaS 形态执行）──
        migrations.RunPython(backfill_and_seed, migrations.RunPython.noop),
    ]
