# Generated by Django 5.1.15 on 2026-09-11 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_p4_auth012_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorySyncRun',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('channel', models.CharField(choices=[('ldap', 'LDAP/AD'), ('scim', 'SCIM 2.0')], max_length=8)),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('dry_run', '干跑'), ('confirmed', '干跑已确认')], default='running', max_length=12)),
                ('is_dry_run', models.BooleanField(default=False)),
                ('full_sync', models.BooleanField(default=False)),
                ('triggered_by', models.CharField(default='beat', max_length=16)),
                ('counts', models.JSONField(default=dict)),
                ('detail', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'directory_sync_run',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectoryPendingAction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('kind', models.CharField(choices=[('pending_provision', '待开通（席位满）'), ('manual_review', '人工裁决（疑似同人）')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('dedup_key', models.CharField(max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('resolved_action', models.CharField(blank=True, max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.directorysyncrun')),
            ],
            options={
                'db_table': 'directory_pending_action',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectoryUserMapping',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('channel', models.CharField(choices=[('ldap', 'LDAP/AD'), ('scim', 'SCIM 2.0')], max_length=8)),
                ('external_id', models.CharField(max_length=128)),
                ('email_snapshot', models.EmailField(max_length=254)),
                ('absence_count', models.PositiveSmallIntegerField(default=0)),
                ('disabled_at_source', models.CharField(blank=True, max_length=16)),
                ('identity_source', models.CharField(default='directory', max_length=16)),
                ('is_sync_protected', models.BooleanField(default=False)),
                ('restore_snapshot', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_mappings', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'directory_user_mapping',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LdapDirectoryConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64)),
                ('server_uri', models.CharField(max_length=255)),
                ('bind_dn', models.CharField(max_length=255)),
                ('bind_secret_ref', models.CharField(max_length=128)),
                ('base_dn', models.CharField(max_length=255)),
                ('user_filter', models.CharField(default='(&(objectClass=user)(mail=*))', max_length=512)),
                ('attribute_map', models.JSONField(default=dict)),
                ('group_map', models.JSONField(default=list)),
                ('sync_interval_minutes', models.PositiveSmallIntegerField(default=15)),
                ('use_starttls', models.BooleanField(default=False)),
                ('sync_cursor', models.CharField(blank=True, max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldap_configs', to='db.workspace')),
            ],
            options={
                'db_table': 'directory_ldap_config',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScimConnector',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(max_length=8)),
                ('attribute_map', models.JSONField(default=dict)),
                ('group_map', models.JSONField(default=list)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_connectors', to='db.workspace')),
            ],
            options={
                'db_table': 'directory_scim_connector',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='directorysyncrun',
            index=models.Index(fields=['workspace', '-created_at'], name='idx_dir_run_ws_created'),
        ),
        migrations.AddIndex(
            model_name='directorypendingaction',
            index=models.Index(fields=['workspace', 'kind', 'status'], name='idx_dir_pending_ws'),
        ),
        migrations.AddConstraint(
            model_name='directorypendingaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('workspace', 'kind', 'dedup_key'), name='uq_pending_action_dedup'),
        ),
        migrations.AddIndex(
            model_name='directoryusermapping',
            index=models.Index(fields=['workspace', 'email_snapshot'], name='idx_dir_mapping_email'),
        ),
        migrations.AddConstraint(
            model_name='directoryusermapping',
            constraint=models.UniqueConstraint(fields=('workspace', 'channel', 'external_id'), name='uq_directory_identity'),
        ),
        migrations.AddConstraint(
            model_name='ldapdirectoryconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_enabled', True)), fields=('workspace',), name='uq_ldap_enabled_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='scimconnector',
            constraint=models.UniqueConstraint(condition=models.Q(('is_enabled', True)), fields=('workspace',), name='uq_scim_enabled_per_workspace'),
        ),
    ]
