# Generated by Django 5.1.15 on 2026-09-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_p4_auth011_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('number', '数字'), ('select', '单选下拉'), ('multi_select', '多选下拉'), ('date', '日期'), ('member', '人员单选'), ('member_multi', '人员多选'), ('checkbox', '复选框'), ('url', 'URL 链接'), ('currency', '金额'), ('auto_increment', '自增编号'), ('cascade', '级联下拉'), ('relation', '关联工作项'), ('date_range', '日期区间'), ('attachment', '附件'), ('formula', '公式计算'), ('cascade_multi', '多级级联（2-5 级）'), ('relation_xproject', '跨项目关联')], help_text='决定表单控件、筛选控件与值的 JSON 类型，创建后不可修改（BR-06）', max_length=24, verbose_name='字段类型'),
        ),
    ]
