# Generated by Django 5.1.15 on 2026-09-12 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_p4_task014_field_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=255, verbose_name='变更原因')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('building', '创建中'), ('ready', '就绪'), ('failed', '失败')], default='building', max_length=10)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('stats_cache', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='db.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'baseline',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaselineItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('sequence_id', models.PositiveIntegerField()),
                ('name_snapshot', models.CharField(max_length=512)),
                ('start_date', models.DateField(null=True)),
                ('target_date', models.DateField(null=True)),
                ('estimate_minutes', models.PositiveIntegerField(null=True)),
                ('assignee_ids', models.JSONField(default=list)),
                ('state_group', models.CharField(max_length=16)),
                ('is_critical', models.BooleanField(default=False)),
                ('total_float_days', models.IntegerField(null=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.baseline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_items', to='db.issue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'baseline_item',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='baseline',
            index=models.Index(fields=['project', '-created_at'], name='idx_baseline_project'),
        ),
        migrations.AddConstraint(
            model_name='baseline',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uq_baseline_project_name'),
        ),
        migrations.AddIndex(
            model_name='baselineitem',
            index=models.Index(fields=['baseline', 'issue'], name='idx_baseline_item_pair'),
        ),
        migrations.AddConstraint(
            model_name='baselineitem',
            constraint=models.UniqueConstraint(fields=('baseline', 'issue'), name='uq_baseline_item_issue'),
        ),
    ]
