# Generated by Django 5.1.15 on 2026-09-12 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_p4_intg004_openapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueMeeting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('meeting_id', models.CharField(db_index=True, max_length=32)),
                ('join_url', models.URLField(max_length=512)),
                ('topic', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'integration_issue_meetings',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlackChannelSubscription',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('channel_id', models.CharField(max_length=32)),
                ('channel_name', models.CharField(max_length=128)),
                ('event_types', models.JSONField(default=list)),
                ('thread_sync', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'integration_slack_subscriptions',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlackMessageAnchor',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('channel_id', models.CharField(max_length=32)),
                ('message_ts', models.CharField(max_length=32)),
                ('thread_ts', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'db_table': 'integration_message_anchors',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlackUserMap',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('slack_user_id', models.CharField(max_length=32)),
                ('slack_email', models.EmailField(max_length=254)),
                ('slack_display_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'integration_slack_user_maps',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoomConnector',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('account_id', models.CharField(max_length=64)),
                ('client_id', models.CharField(max_length=64)),
                ('client_secret_ref', models.CharField(max_length=128)),
                ('webhook_secret_ref', models.CharField(max_length=128)),
                ('ai_minutes_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'integration_zoom_connectors',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='integrationinstallation',
            name='uniq_binding_project_repo_active',
        ),
        migrations.RemoveConstraint(
            model_name='integrationinstallation',
            name='chk_repo_name',
        ),
        migrations.AddField(
            model_name='integrationinstallation',
            name='bot_token_ref',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='密保库 bot token 句柄'),
        ),
        migrations.AddField(
            model_name='integrationinstallation',
            name='bot_user_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='integrationinstallation',
            name='credentials_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='integrationinstallation',
            name='team_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Slack team id'),
        ),
        migrations.AddField(
            model_name='integrationinstallation',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='integrationinstallation',
            name='unbound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationinstallation',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='db.workspace'),
        ),
        migrations.AlterField(
            model_name='integrationinstallation',
            name='installation_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='GitHub installation id'),
        ),
        migrations.AlterField(
            model_name='integrationinstallation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='db.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='integrationinstallation',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('slack', 'Slack'), ('zoom', 'Zoom')], default='github', max_length=16, verbose_name='集成提供方'),
        ),
        migrations.AlterField(
            model_name='integrationinstallation',
            name='repository_full_name',
            field=models.CharField(blank=True, default='', help_text='owner/repo，小写（GitHub 行专用）', max_length=200, verbose_name='仓库全名'),
        ),
        migrations.AddConstraint(
            model_name='integrationinstallation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('provider', 'github')), fields=('project', 'repository_full_name'), name='uniq_binding_project_repo_active'),
        ),
        migrations.AddConstraint(
            model_name='integrationinstallation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('repository_full_name', ''), _negated=True), models.Q(('provider', 'github'), _negated=True), _connector='OR'), name='chk_repo_name'),
        ),
        migrations.AddConstraint(
            model_name='integrationinstallation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('provider', 'slack'), ('team_id__gt', '')), fields=('team_id',), name='uq_slack_team_ws'),
        ),
        migrations.AddField(
            model_name='issuemeeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuemeeting',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='db.issue'),
        ),
        migrations.AddField(
            model_name='issuemeeting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='slackchannelsubscription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='slackchannelsubscription',
            name='installation',
            field=models.ForeignKey(limit_choices_to={'provider': 'slack'}, on_delete=django.db.models.deletion.CASCADE, related_name='slack_subscriptions', to='db.integrationinstallation'),
        ),
        migrations.AddField(
            model_name='slackchannelsubscription',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.project'),
        ),
        migrations.AddField(
            model_name='slackchannelsubscription',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='slackmessageanchor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='slackmessageanchor',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_anchors', to='db.issue'),
        ),
        migrations.AddField(
            model_name='slackmessageanchor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='slackusermap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='slackusermap',
            name='installation',
            field=models.ForeignKey(limit_choices_to={'provider': 'slack'}, on_delete=django.db.models.deletion.CASCADE, to='db.integrationinstallation'),
        ),
        migrations.AddField(
            model_name='slackusermap',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='slackusermap',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zoomconnector',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='zoomconnector',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddIndex(
            model_name='issuemeeting',
            index=models.Index(fields=['meeting_id'], name='idx_issue_meeting_mid'),
        ),
        migrations.AddConstraint(
            model_name='slackmessageanchor',
            constraint=models.UniqueConstraint(fields=('issue', 'channel_id'), name='uq_slack_anchor_channel'),
        ),
        migrations.AddConstraint(
            model_name='slackusermap',
            constraint=models.UniqueConstraint(fields=('installation', 'slack_user_id'), name='uq_slack_user_map'),
        ),
        migrations.AddConstraint(
            model_name='zoomconnector',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('account_id',), name='uq_zoom_connector_active'),
        ),
    ]
