# Generated by Django 5.1.15 on 2026-09-12 03:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_im_sub_uniq_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='dlp_hits',
            field=models.JSONField(blank=True, default=list, verbose_name='DLP 命中规则名'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='合规 purge 标记时间'),
        ),
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('watermark', models.CharField(max_length=24, null=True)),
                ('download', models.CharField(max_length=16, null=True)),
                ('share_link', models.CharField(max_length=20, null=True)),
                ('retention_days', models.PositiveIntegerField(null=True)),
                ('dark_watermark', models.BooleanField(null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.fileasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.filefolder')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'file_compliance_policy',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', 'project', 'folder'], name='idx_policy_ws_overrides')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', True), ('folder__isnull', True), ('project__isnull', True), ('workspace__isnull', False)), models.Q(('asset__isnull', True), ('folder__isnull', True), ('project__isnull', False)), models.Q(('asset__isnull', True), ('folder__isnull', False)), ('asset__isnull', False), _connector='OR'), name='ck_policy_exactly_one_scope'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('workspace__isnull', False)), fields=('workspace',), name='uq_policy_workspace'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', False)), fields=('project',), name='uq_policy_project'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('folder__isnull', False)), fields=('folder',), name='uq_policy_folder'), models.UniqueConstraint(condition=models.Q(('asset__isnull', False), ('deleted_at__isnull', True)), fields=('asset',), name='uq_policy_asset')],
            },
        ),
        migrations.CreateModel(
            name='DlpRule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64)),
                ('pattern', models.CharField(max_length=512)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlp_rules', to='db.workspace')),
            ],
            options={
                'db_table': 'file_dlp_rule',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', 'is_enabled'], name='idx_dlp_rule_ws_enabled')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='uq_dlp_rule_ws_name')],
            },
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('reason', models.CharField(max_length=255)),
                ('case_ref', models.CharField(blank=True, max_length=64)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_holds', to='db.fileasset')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table': 'file_legal_hold',
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('asset',), name='uq_legal_hold_active')],
            },
        ),
    ]
