# Generated by Django 5.1.15 on 2026-09-12 04:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0049_p4_rpt005_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCallLedger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('capability', models.CharField(max_length=16)),
                ('provider', models.CharField(max_length=24)),
                ('model', models.CharField(max_length=48)),
                ('outbound_fields', models.JSONField(default=dict)),
                ('prompt_hash', models.CharField(max_length=64)),
                ('tokens', models.JSONField(default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=8)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'ai_call_ledgers',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='idx_ai_ledger_ws')],
            },
        ),
        migrations.CreateModel(
            name='AiConsent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('consent_version', models.CharField(max_length=8)),
                ('capabilities', models.JSONField(default=list)),
                ('provider_policy', models.CharField(max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'ai_consents',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='idx_ai_consent_ws')],
            },
        ),
        migrations.CreateModel(
            name='AiFeedback',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('capability', models.CharField(max_length=16)),
                ('verdict', models.CharField(max_length=8)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.issue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'ai_feedbacks',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='idx_ai_feedback_ws')],
            },
        ),
        migrations.CreateModel(
            name='AiQuotaCounter',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('capability', models.CharField(max_length=16)),
                ('quota_date', models.DateField()),
                ('used', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'ai_quota_counters',
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('workspace', 'capability', 'quota_date'), name='uq_ai_quota_ws_cap_date')],
            },
        ),
        migrations.CreateModel(
            name='IssueRiskScore',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('score', models.PositiveSmallIntegerField()),
                ('top_reasons', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('model_version', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=8)),
                ('computed_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.issue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'issue_risk_scores',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['issue', '-computed_at'], name='idx_risk_score_issue')],
            },
        ),
    ]
